packages/transition-backend/src/models/db/__tests__/dataSources.db.test.ts, packages/transition-backend/src/models/db/dataSources.db.queries.ts
Backported from octavi. Useful for tasks requiring a data source argument, to fetch a data source by name or shortname.
=> dataSources: Add a findByName db query

packages/chaire-lib-backend/package.json
The yarn scripts require babel-node. From this repo, it runs fine without it, but when importing with submodules, this dependency is required.
=> chaire-lib-backend: Add @babel/cli dependency

packages/chaire-lib-backend/src/scripts/config/setup.task.ts
Fixes #457
In recent postgresql versions (at least on 14+), dropping the operator class is not sufficient to clean up everything and when re-creating it, there's an exception for a duplicate key in the pg_amop table. This prevents the setup task to be run more than once.
Dropping the operator family fixes the issue. It works also on old versions of postgresql.
=> setup: Drop operator family as well as class

.env.example, .github/workflows/transition.yml, examples/README.md, package.json, packages/chaire-lib-backend/src/config/__tests__/server.config.noenv.test.ts, packages/chaire-lib-backend/src/config/auth/index.ts, packages/chaire-lib-backend/src/config/auth/localLogin.config.ts, packages/chaire-lib-backend/src/config/auth/passport.utils.ts, packages/chaire-lib-backend/src/config/dotenv.config.ts, packages/chaire-lib-backend/src/config/knexfile.ts, packages/chaire-lib-backend/src/config/server.config.ts, packages/chaire-lib-backend/src/scripts/config/createUser.task.ts, packages/chaire-lib-backend/src/scripts/config/knexfile.public.ts, packages/chaire-lib-backend/src/scripts/config/knexfile.root.ts, packages/chaire-lib-backend/src/scripts/config/setup.task.ts, packages/chaire-lib-backend/src/tasks/taskWrapper.ts, packages/chaire-lib-backend/src/utils/filesystem/directoryManager.ts, packages/transition-backend/src/scripts/cache/recreateCache.task.ts, packages/transition-backend/src/scripts/listTasks.task.ts, packages/transition-backend/src/scripts/simulations/simulation.task.ts, packages/transition-backend/src/server.ts, packages/transition-backend/src/serverApp.ts, packages/transition-frontend/webpack.config.js
Fixes #425
First, we check if the PROJECT_CONFIG environment variable contains the
path to the config file. Otherwise, it is expected to be in the
$homedir/.config/transition/config.js or /etc/transition/config.js.
The path in the .env now has to be absolute. ${rootDir} works only in
the current repository, but chaire-lib is meant as a library, so rootDir
will not work for those.
Add a start:demo script in the package.json which sets the
PROJECT_CONFIG environment variable to the example config.
=> config: Add default paths for project config file

packages/chaire-lib-backend/src/config/dotenv.config.ts, packages/transition-backend/package.json
The infrastructures just set the environment variables and do not need the .env file.
=> config: Allow the .env file to not exist

packages/chaire-lib-backend/src/utils/processManagers/OSRMProcessManager.ts, packages/chaire-lib-backend/src/utils/processManagers/OSRMServicePreparation.ts
osrm-contract expect the file prefix when starting. I don't know how the previous command worked
=> Fix start of osrm-contract

packages/transition-backend/src/services/accessMapLocation/AccessMapLocationProvider.ts, packages/transition-backend/src/services/odTrip/odTripProvider.ts, packages/transition-backend/src/services/transitRouting/TrAccessibilityMapBatch.ts, packages/transition-backend/src/services/transitRouting/TrRoutingBatch.ts, packages/transition-backend/src/services/transitRouting/TrRoutingOdTrip.ts
Each odTrip calculated was logged when read and when calculated. For large input files, that is a lot of log lines, that are useless for debugging and any actual error logged during the execution is kicked out of the log buffer.
Log entries at read time are shown only if the debug option is set to true. Execution logs are shown for every 1% progress.
=> batchRouting: Reduce the amount of logging in batch calculations

packages/chaire-lib-common/src/utils/objects/Saveable.ts, packages/chaire-lib-frontend/src/components/pageParts/SelectedObjectButtons.tsx
The typeguard avoids having to cast the object before using it as Saveable.
=> chaire-lib: Use a proper typeguard for the `isSaveable` method

packages/chaire-lib-frontend/package.json
chaire-lib packages do not depend on transition.
=> Remove transition-common dependency from chaire-lib-frontend

packages/chaire-lib-common/src/api/TrRouting/index.ts, packages/chaire-lib-common/src/api/TrRouting/trRoutingApiV2.ts, packages/chaire-lib-common/src/services/trRouting/TrRoutingService.ts
The API has recently changed for the summary call, with a `query` and `result` fields in the json response instead of everything at the root.
=> trRouting: Update the summary return type to match the v2 api

packages/chaire-lib-frontend/src/styles/_collapsible.scss
Fixes #494
This bug occurred since the upgrade to react-collapsible 2.10
On first click to a lazy rendered element, the height is 0 and the children are not expanded. Only on third click did it show. It is a bug in the react-collapsible library (see
https://github.com/glennflanagan/react-collapsible/issues/36)
To bypass this, add a 1px padding on top of the collapsible's inner content, to make sure the chilren have a height.
=> Fix the Collapsible lazy rendered elements not displaying

packages/transition-backend/src/services/transitRouting/TrRoutingOdTrip.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrRoutingOdTrip.test.ts
Fixes #487
The trRouting API v1 inverses the latitude and longitude order in the response.
=> batchRouting: Fix mix up of lat/lon in batch routing result files

packages/chaire-lib-common/src/services/trRouting/TrRoutingService.ts
The error now simply says: "cannot calculate transit route with
trRouting: <status>". It is not very helpful for debugging.
=> trRouting: Add extra logging to trRouting's error unknown.

.env.docker, Dockerfile, README.md, docker-compose.yml, examples/config.js
* Copy the .env.example file to .env before the rest, to not override the .env file
* Add edit suggestions to the `docker-compose.yml` file for common use cases
* Update the docker section of the README with additional documentation, as it does not work out of the box and needs some tweaking.
=> Improve the docker startup workflow and documentation

packages/transition-backend/src/services/gtfsExport/LineExporter.ts, packages/transition-backend/src/services/gtfsExport/__tests__/LineExporter.test.ts, packages/transition-backend/src/services/gtfsImport/AgencyImporter.ts, packages/transition-backend/src/services/gtfsImport/GtfsImportTypes.ts, packages/transition-backend/src/services/gtfsImport/LineImporter.ts, packages/transition-backend/src/services/gtfsImport/ServiceImporter.ts, packages/transition-backend/src/services/gtfsImport/__tests__/GtfsImportData.test.ts, packages/transition-backend/src/services/gtfsImport/__tests__/LineImporter.test.ts
Fixes #505
In Transition, color fields are prefixed with '#', but in the gtfs specification, colors are the 6 hexadecimal digits of the colors. A helper method takes care of converting the color in the right format during import and exports removes the '#' prefix.
=> gtfs: Fix format of color in GTFS import/export

packages/chaire-lib-frontend/src/styles/_main.scss, packages/transition-frontend/src/components/map/TransitionMainMap.tsx
Fixes #500
These were already styled in the tr__main-map-context-menu and it makes sense to add elements as a list in this case.
=> map: Use ul/li in the main map context menu

packages/transition-frontend/src/components/forms/transitRouting/RoutingResultsComponent.tsx, packages/transition-frontend/src/components/forms/transitRouting/TransitRoutingForm.tsx
Fixes #528
Propagates the currently selected mode to the main transit calculation form and pass it to the results component.
=> Route calculation: Keep the selected tab between calculation

locales/en/transit.json, locales/fr/transit.json, packages/chaire-lib-frontend/src/components/forms/ChangeEventsForm.tsx, packages/transition-frontend/src/components/forms/transitRouting/TransitRoutingBatchForm.tsx, packages/transition-frontend/src/components/forms/transitRouting/TransitRoutingForm.tsx
Fixes #538
If scenario is not set or any other routing parameter field is invalid, add an error message when the user clicks on the batch calculation button to validate the routing parameters first.
=> transit routing: Make sure parameters are valid before batch

packages/chaire-lib-frontend/src/components/input/FileUploaderHOC.tsx, packages/transition-frontend/src/components/forms/accessibilityMap/AccessibilityMapBatchForm.tsx, packages/transition-frontend/src/components/forms/agency/TransitAgencyImportForm.tsx, packages/transition-frontend/src/components/forms/line/TransitLineImportForm.tsx, packages/transition-frontend/src/components/forms/node/TransitNodeImportForm.tsx, packages/transition-frontend/src/components/forms/path/TransitPathImportForm.tsx, packages/transition-frontend/src/components/forms/scenario/TransitScenarioImportForm.tsx, packages/transition-frontend/src/components/forms/service/TransitServicesImportForm.tsx, packages/transition-frontend/src/components/forms/transitRouting/TransitRoutingBatchForm.tsx, packages/transition-frontend/src/components/parts/FileImportForm.tsx
1- Type the FileUploaderHOC's props and have consumers extend those props instead of redefining them
2- Let the FileImportForm use the FileUploaderHOC directly instead of every form using it
=> Clean up the file uploader HOC

packages/chaire-lib-backend/src/models/db/default.db.queries.ts, packages/transition-backend/src/models/db/__tests__/TransitPath.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitNodes.db.test.ts, packages/transition-backend/src/models/db/transitNodes.db.queries.ts, packages/transition-backend/src/models/db/transitSchedules.db.queries.ts
Fixes #562
In effect, sometimes, this function is called with an array of fields to return. If it is the case, the returned object is expected to be an object.
cc @nik498
=> db: Let the `create` function's returning parameter be an array too

packages/transition-common/src/services/accessibilityMap/TransitBatchAccessibilityMap.ts, packages/transition-common/src/services/transitDemand/TransitDemandFromCsv.ts, packages/transition-common/src/services/transitDemand/TransitOdDemandFromCsv.ts, packages/transition-common/src/services/transitDemand/__tests__/TransitOdDemandFromCsv.test.ts, packages/transition-frontend/src/components/forms/accessibilityMap/AccessibilityMapBatchForm.tsx, packages/transition-frontend/src/components/forms/transitRouting/TransitRoutingBatchForm.tsx, packages/transition-frontend/src/components/forms/transitRouting/widgets/TransitRoutingBaseComponent.tsx
The csvFile attribute can be a string or a File object. Also, setting
and parsing the file to make sure current attribute mapping is still
valid can be done in the common workspace, where it can be used by all
consumers, instead of in the forms.
=> transitDemand: Type the csvFile attribute and handle fields in base class

locales/en/main.json, locales/en/transit.json, locales/fr/main.json, locales/fr/transit.json, packages/chaire-lib-common/src/config/defaultPreferences.config.ts, packages/transition-common/src/services/transitDemand/TransitDemandFromCsv.ts, packages/transition-frontend/src/app-transition.tsx, packages/transition-frontend/src/components/dashboard/supplyDemandAnalysisModule/SupplyDemandAnalysisDashboardContribution.tsx, packages/transition-frontend/src/components/forms/batchCalculation/BatchCalculationForm.tsx, packages/transition-frontend/src/components/forms/batchCalculation/BatchCalculationList.tsx, packages/transition-frontend/src/components/forms/batchCalculation/BatchCalculationPanel.tsx, packages/transition-frontend/src/components/forms/batchCalculation/stepForms/ConfigureBatchCalculationForm.tsx, packages/transition-frontend/src/components/forms/batchCalculation/stepForms/ConfigureDemandFromCsvForm.tsx, packages/transition-frontend/src/components/forms/batchCalculation/stepForms/ConfirmCalculationForm.tsx, packages/transition-frontend/src/components/forms/transitRouting/TransitRoutingBatchForm.tsx, packages/transition-frontend/src/services/batchCalculation/__tests__/types.test.ts, packages/transition-frontend/src/services/batchCalculation/types.ts, packages/transition-frontend/src/services/transitDemand/types.ts
* Add a new section, "Scenario analysis", which is part of the "supply/demand analysis" module.
* The current batch routing functionality is moved to this new section as follows:
- The main panel displays by default the list of batchRouting tasks that belongs to the user. It also contains a button to do a new analysis
- The new analysis button opens a 3-steps wizard, where the user can 
1- select the demand CSV file and map the fields, 
2- Specify the calculation parameters (travel times, scenario, withAlternatives) 
3- Visualize the various parameters and either go back to modify or click Calculate. Clicking calculate triggers the calculation and the user is back to the job list and can see the progress.
* The current batch calculation is replaced by a message telling the user to go to …
=> Scenario Analysis: Move the batch routing feature to a Scenario analysis section

packages/chaire-lib-common/src/config/osm/overpassQueries/allNodes.overpassql, packages/chaire-lib-common/src/config/osm/overpassQueries/allNodes.ts, packages/chaire-lib-common/src/config/osm/overpassQueries/allWaysAndRelations.overpassql, packages/chaire-lib-common/src/config/osm/overpassQueries/allWaysAndRelations.ts
We were getting timeout trying to download bigger regions like LA. Doubling the time allows the queries to complete.
=> Increase overpass queries timeout

.env.example, packages/transition-backend/src/models/db/__tests__/jobs.db.test.ts, packages/transition-backend/src/models/db/jobs.db.queries.ts, packages/transition-backend/src/services/executableJob/ExecutableJob.ts, packages/transition-backend/src/services/executableJob/__tests__/ExecutableJob.test.ts, packages/transition-backend/src/socketServerApp.ts, packages/transition-backend/src/tasks/TransitionWorkerPool.ts
Fixes #476
This enqueues any executable jobs that are in progress or pending when
the server starts so they can be run again. In progress jobs are simply
restarted, running jobs are enqueued first, then the pending ones
ordered by the creation time, earliest first.
Add unit tests for resume functions and queries with multiple sort options
=> jobs: Allow to restart running and pending jobs when server restarts

packages/transition-frontend/src/components/forms/transitRouting/TransitRoutingResultComponent.tsx
When the previous trRouting v1 API was directly used in the result, the departure and arrival times were already formatted, they are now in seconds since midnight and need to be formatted at display time.
=> routing results: Fix formatting of departure and arrival times

packages/transition-backend/src/models/db/__tests__/jobs.db.test.ts, packages/transition-backend/src/services/executableJob/__tests__/ExecutableJob.test.ts, packages/transition-backend/src/services/gtfsExport/__tests__/LineExporter.test.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrRoutingOdTrip.test.ts
The imports were mistakenly imported from the src/ directory instead of lib
=> Fix imports from transition-common package to lib in tests

packages/transition-frontend/package.json, packages/transition-frontend/src/components/parts/executableJob/ExecutableJobComponent.tsx
Add a customActions prop to the ExecutableJobComponent, which takes a callback with the jobId, a title string and an icon to represent the job. This icon is added before the `delete` icon in the actions cell.
=> jobs: Support custom action in the UI's job list

locales/en/transit.json, locales/fr/transit.json, packages/chaire-lib-common/src/api/TrRouting/base.ts, packages/chaire-lib-common/src/api/TrRouting/index.ts, packages/transition-backend/src/api/__tests__/services.socketRoutes.test.ts, packages/transition-backend/src/api/services.socketRoutes.ts, packages/transition-backend/src/services/executableJob/ExecutableJob.ts, packages/transition-backend/src/services/executableJob/__tests__/ExecutableJob.test.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrAccessibilityMapBatch.test.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrRoutingBatch.test.ts, packages/transition-common/src/services/transitDemand/TransitDemandFromCsv.ts, packages/transition-common/src/services/transitDemand/__tests__/TransitOdDemandFromCsv.test.ts, packages/transition-common/src/services/transitRouting/TransitBatchRoutingCalculator.ts, packages/transition-common/src/services/transitRouting/__tests__/TransitBatchRoutingCalculator.test.ts, packages/transition-frontend/src/components/forms/accessibilityMap/AccessibilityMapBatchForm.tsx, packages/transition-frontend/src/components/forms/batchCalculation/BatchCalculationForm.tsx, packages/transition-frontend/src/components/forms/batchCalculation/BatchCalculationList.tsx, packages/transition-frontend/src/components/forms/batchCalculation/BatchCalculationPanel.tsx, packages/transition-frontend/src/components/forms/batchCalculation/stepForms/ConfigureDemandFromCsvForm.tsx, packages/transition-frontend/src/components/forms/batchCalculation/stepForms/ConfirmCalculationForm.tsx, packages/transition-frontend/src/services/accessibilityMap/BatchAccessibilityMapCalculator.ts
Let the demand support either a file coming from upload or from a preceding task on server.
Add a custom action to the batch calculation tasks list to create a new calculation from this task. It fetches the task's parameter, as well as the csv fields in the file and opens the new calculation form with those initial values.
=> batchCalculation: Create a new calculation from an existing one

package.json, packages/transition-backend/src/api/all.socketRoutes.ts, packages/transition-backend/src/api/dataSources.socketRoutes.ts, packages/transition-backend/src/models/db/__tests__/dataSources.db.test.ts, packages/transition-backend/src/models/db/dataSources.db.queries.ts, packages/transition-backend/src/models/db/migrations/20230315184600_addDataSourceOwner.ts, packages/transition-backend/src/services/dataSources/__tests__/dataSources.test.ts, packages/transition-backend/src/services/dataSources/dataSources.ts, packages/transition-backend/src/services/simulation/methods/AccessibilityMapSimulation.ts, packages/transition-backend/src/services/simulation/methods/OdTripSimulation.ts, packages/transition-common/src/services/dataSource/DataSource.ts
Add a `owner` column to the data source, which can be null (for global data sources), or a foreign key to the userId. Queries are updated so they take an optional userId parameter to retrieve only allowed data sources (since data sources are currently mostly used in tasks, like simulations, which do not have a userId, we can't make this parameter mandatory for now).
For now, the main intention is to allow users to import private odTrip data, without sharing it with all users (odTrip import feature is currently not working, but when it is brought back, the option to import a global data source (with null owner) will be available)
=> dataSources: Add a data source owner to allow private data sources

packages/transition-backend/src/services/executableJob/ExecutableJob.ts, packages/transition-backend/src/services/executableJob/__tests__/ExecutableJob.test.ts
The await for the enqueue effectively waits for the whole job to be complete! This is not desired.
=> jobs: Remove await from job when restarted at the beginning

packages/transition-backend/src/services/executableJob/ExecutableJob.ts
Fixes #615
When enqueueing pending and inProgress jobs, the order needs to be respected, so we need to wait for the enqueue to complete, but the enqueue should not return the Promise object that waits for the job completion.
=> jobs: Wait for the save when enqueueing jobs at startup

packages/transition-backend/src/services/transitRouting/ResultAttributes.ts, packages/transition-backend/src/services/transitRouting/TrRoutingBatch.ts, packages/transition-backend/src/services/transitRouting/TrRoutingBatchResult.ts, packages/transition-backend/src/services/transitRouting/TrRoutingOdTrip.ts, packages/transition-backend/src/services/transitRouting/__tests__/ResultAttributes.test.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrRoutingBatch.test.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrRoutingBatchResult.test.ts, packages/transition-backend/src/services/transitRouting/types.ts, packages/transition-backend/src/tasks/TransitionWorkerPool.ts
As part of the work to handle checkpoints and job resume, this extracts the result handling to its own class, like it is already done in the batch accessibility map calculation.
The main batchRoute method is refactored to be handled by a class, with parameters and options as local fields, that can more easily be split in modular chunks
=> batchRoute: Refactor result handling

packages/transition-backend/src/api/__tests__/jobs.socketRoutes.test.ts, packages/transition-backend/src/models/db/__tests__/jobs.db.test.ts, packages/transition-backend/src/models/db/jobs.db.queries.ts, packages/transition-backend/src/models/db/migrations/20230309104300_addJobsInternalData.ts, packages/transition-backend/src/services/executableJob/ExecutableJob.ts, packages/transition-backend/src/services/executableJob/JobCheckpointTracker.ts, packages/transition-backend/src/services/executableJob/__tests__/ExecutableJob.test.ts, packages/transition-backend/src/services/executableJob/__tests__/JobCheckpointTracker.test.ts, packages/transition-backend/src/services/transitRouting/TrRoutingBatch.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrRoutingBatch.test.ts, packages/transition-backend/src/tasks/TransitionWorkerPool.ts, packages/transition-common/src/services/jobs/Job.ts, packages/transition-common/src/services/jobs/__tests__/Job.test.ts
Add an internal_data field to jobs to keep the checkpoint, and eventually all other internal data that the user is not meant to see.
Implement a checkpoint mechanism to track completion of potentially out of order steps of a task.
Let the batchRoute function use this checkpoint tracker mechanism to resume the task
Note that the results are not deleted from the database anymore, as there may be a point in the job execution where the files are generated, the results are deleted, but the job is not yet marked as completed. If the server is shut down at that moment, the results won't be recoverable for this job. We would need some other mechanism to properly complete the task. Besides, jobs are not meant to be kept forever, they will fill the user quota anyway. Results will be deleted when …
=> batchRoute: Allow batch routing jobs to be resumed

packages/chaire-lib-backend/jest.config.js, packages/chaire-lib-backend/jestSetup.ts, packages/chaire-lib-backend/src/config/shared/__mocks__/db.config.ts, packages/transition-backend/jest.config.js, packages/transition-backend/jestSetup.ts, packages/transition-backend/src/models/db/__tests__/batchRouteResults.db.test.ts
Fixes #633
In unit tests testing files that import database query files, the database configuration is always loaded and requires the .env file to have been parsed with proper data. This should not be a requirement to run tests, especially that the database queries that are under test are already mocked. This adds a mock for the db.config, which simply initializes a dummy knex object for 'sqlite' that should make the tests pass without configuration.
The `db.config` file is automatically mocked in chaire-lib-backend and transition-backend packages.
=> tests: Mock the db.config file

docs/ABC_of_pull_requests.md, packages/chaire-lib-backend/src/config/auth/passport.utils.ts, packages/chaire-lib-backend/src/models/db/__tests__/users.db.test.ts, packages/chaire-lib-backend/src/models/db/users.db.queries.ts
This would fix issue #549 .
This has been tested through the command line with yarn create-user and through the registration form. Both reject the creation of a new user when emails or usernames are identical, regardless of the case.
=> Fix case insensitive emails

packages/chaire-lib-backend/src/config/auth/index.ts, packages/chaire-lib-backend/src/services/auth/authModel.ts
User deserialization is for backend only, so all users attributes can be returned instead of just a sanitized version. That was the previous implementation, before supporting multiple authentication models. It was changed, but the admin users now cannot have proper authorization in evolution, so attributes are returned again.
=> auth: Deserialize users with all attributes

packages/transition-backend/src/serverApp.ts
In this initialization, `passport` is also initialized and it needs to be initialized before adding the get/set routes that require user authentication. So it is moved up the initialization process.
=> auth: Move the authRoute initialization up

packages/chaire-lib-backend/src/config/auth/__tests__/localLogin.config.test.ts, packages/chaire-lib-backend/src/config/auth/__tests__/passwordless.config.test.ts, packages/chaire-lib-backend/src/services/auth/__tests__/anonymousLoginStrategy.test.ts, packages/chaire-lib-backend/src/services/auth/__tests__/userAuthModel.test.ts, packages/chaire-lib-backend/src/services/auth/authModel.ts, packages/chaire-lib-backend/src/services/auth/userAuthModel.ts, packages/chaire-lib-backend/src/tasks/user/__tests__/createUser.test.ts, packages/chaire-lib-backend/src/tasks/user/createUser.ts
Also support preferences, first and last names for the user creation (which probably once worked but were broken).
Add unit tests for the createUser task
=> Fix the is_admin flag of the create-user task

packages/chaire-lib-frontend/src/components/pageParts/Header.tsx, packages/chaire-lib-frontend/src/config/application.config.ts, packages/chaire-lib-frontend/src/styles/_header.scss, packages/transition-frontend/src/app-transition.tsx
The current user menu, when clicking on the username on the header, contains a single element, that resets the session. It was done quickly for a requirement in Octavi, but it does not make much sense in Transition or Evolution surveys.
This commit adds a mechanism in the application configuration, where the application can set various menu items that will go in this user menu. In the Transition configuration, we have a single menu item that opens the Preferences edit form.
=> chaire-lib: Allow applications to specify menu items under users

packages/chaire-lib-common/src/config/Preferences.ts, packages/chaire-lib-common/src/config/__tests__/Preferences.test.ts, packages/chaire-lib-frontend/src/actions/Auth.tsx, packages/chaire-lib-frontend/src/services/map/events/GlobalMapEvents.ts, packages/transition-common/src/services/accessibilityMap/TransitAccessibilityMapRouting.ts, packages/transition-common/src/services/transitDemand/TransitDemandFromCsv.ts, packages/transition-common/src/services/transitRouting/TransitRouting.ts, packages/transition-frontend/src/components/dashboard/TransitionDashboard.tsx, packages/transition-frontend/src/services/map/PathMapLayerManager.ts
Some preferences methods, like load and update had an optional eventManager parameter which was used to notify of preferences changes. But interested classes need to know about this eventManager and all callers of preferences update/load needed to make sure to pass this specific eventManager. Now, they can register directly to the preferences class, which handles notifications.
=> preferences: Let the class have change listeners

packages/transition-common/src/services/service/Service.ts, packages/transition-common/src/services/service/__tests__/Service.test.ts, packages/transition-frontend/src/services/transitService/__tests__/TransitServiceUtils.test.ts
Fixes #674
This improves the date/range validation for a service:
1- It checks if at least one date in the range is on a service day for
this service.
2- Only dates are considered in addition to the service days, as per the
GTFS specification, instead of the only dates this service is valid.
Unit tests are added to cover those new cases.
=> service: fix isValidForDate method for ranges

locales/en/main.json, locales/fr/main.json, packages/chaire-lib-common/src/services/geodata/ManageOverlappingLines.ts, packages/chaire-lib-common/src/services/geodata/RelocateNodes.ts, packages/chaire-lib-common/src/services/geodata/__tests__/ManageOverlappingLines.test.ts, packages/chaire-lib-common/src/services/geodata/__tests__/RelocateNodes.test.ts, packages/chaire-lib-frontend/src/services/map/events/GlobalMapEvents.ts, packages/transition-frontend/src/components/forms/preferences/PreferencesEdit.tsx, packages/transition-frontend/src/components/forms/preferences/sections/PreferencesSectionFeatures.tsx, packages/transition-frontend/src/components/map/TransitionMainMap.tsx
Offset transit paths on the map to better see where each goes. Offset
stop nodes to be in the middle of crossing paths to see which paths have
a stop there.
It is inspired by this article for by the transit app developers:
https://blog.transitapp.com/how-we-built-the-worlds-prettiest-auto-generated-transit-maps-12d0c6fa502f/
But instead of image processing, the geojson data is processed directly
and modified before display.
This feature is experimental and needs the `features.map.prettyDisplay`
preference to be set.
Also, the transit nodes by which paths pass are placed such that they
are in the middle of the lines.
The overlapping segments take time to calculate, it is done
asynchronously. After zooming or panning, it may take a few seconds
before the map shows the pretty path
Future …
=> UI: Display split lines passing by a same segment

packages/chaire-lib-backend/src/tasks/zones/__tests__/importZonesFromGeojson.test.ts, packages/chaire-lib-backend/src/tasks/zones/importZonesFromGeojson.ts
The shortname substring was causing an exception if the property was, for example, an integer
=> zones: Fix zone import when properties are not string

packages/chaire-lib-backend/src/config/auth/index.ts, packages/chaire-lib-backend/src/services/auth/authModel.ts
fixes #704
It previously looked into the users table only, but other authentication methods, like the evolution's participant login, use another table.
=> auth: use the authModel.find for third party authentication

packages/chaire-lib-backend/src/services/auth/__tests__/anonymousLoginStrategy.test.ts, packages/chaire-lib-backend/src/services/auth/anonymousLoginStrategy.ts
fixes #711
Instead of 6 digits, we use the last 10 characters of a uuid (hex characters) for the "random" part of the username. It also checks if the username exists before assigning it, up to 10 tentatives, after which it fails with a message that a unique name cannot be found.
According to https://zelark.github.io/nano-id-cc/, with the hex alphabet and 10 characters, it should take 148K IDs to have a 1% probability of collision. With 10 checks, it should be enough for most applications using chaire-lib.
=> auth: check is username exists and use part of a uuid as name

packages/chaire-lib-frontend/src/components/forms/auth/localLogin/RegisterForm.tsx, packages/chaire-lib-frontend/src/components/forms/auth/passwordless/PwdLessLoginForm.tsx
fixes #713
Validate that the email field is really an email, as otherwise it won't be possible to go back to an interview.
Also, use the LodashExtension's utility function for isEmail in RegisterForm.
=> auth: Validate email for passwordless login

packages/chaire-lib-frontend/src/components/forms/auth/localLogin/LoginForm.tsx, packages/chaire-lib-frontend/src/components/forms/auth/localLogin/RegisterForm.tsx, packages/chaire-lib-frontend/src/components/forms/auth/passwordless/PwdLessLoginForm.tsx
=> auth: remove trailing space in email on login forms

packages/transition-backend/src/services/transitRouting/TrRoutingOdTrip.ts
fixes #724
The walkOnlyPath is the same as the first walking route, which is already part of the result. This should save some space in the database for the results.
=> batchRoute: Remove the walkOnlyPath from results in DB

packages/transition-frontend/package.json, packages/transition-frontend/webpack.config.js, yarn.lock
This was a very old dependency (not sure how it's actually used) but it was pulling in <https://www.npmjs.com/package/path> and <https://www.npmjs.com/package/fs> (which are actually node core modules).
On the road to a webpack 5 upgrade.
=> Upgrade webpack-glsl-loader.

packages/chaire-lib-frontend/src/components/pageParts/SelectedObjectButtons.tsx, packages/chaire-lib-frontend/src/components/pageParts/__tests__/__snapshots__/SelectedObjectButtons.test.tsx.snap, packages/chaire-lib-frontend/src/styles/_dashboard.scss, packages/chaire-lib-frontend/src/styles/_form.scss, packages/transition-frontend/src/components/forms/agency/TransitAgencyButton.tsx, packages/transition-frontend/src/components/forms/agency/TransitAgencyEdit.tsx, packages/transition-frontend/src/components/forms/line/TransitLineEdit.tsx, packages/transition-frontend/src/components/forms/node/TransitNodeEdit.tsx, packages/transition-frontend/src/components/forms/preferences/PreferencesEdit.tsx, packages/transition-frontend/src/components/forms/scenario/TransitScenarioEdit.tsx, packages/transition-frontend/src/components/forms/service/TransitServiceEdit.tsx, packages/transition-frontend/src/components/forms/simulation/SimulationEdit.tsx
For second commit, looks like this now:
=> Move navigation buttons to top of panel and add margin at the bottom of lines collapsible

packages/transition-backend/src/models/db/__tests__/batchRouteResults.db.test.ts, packages/transition-backend/src/models/db/batchRouteResults.db.queries.ts, packages/transition-backend/src/services/transitRouting/TrAccessibilityMapBatchResult.ts, packages/transition-backend/src/services/transitRouting/TrRoutingBatch.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrRoutingBatch.test.ts
fixes #760
Add a database query to stream batch routing results. This allows to process results one at a time in a streamed way, instead of fixed paged size at once. This might prevent out of memory exceptions for large calculation batches.
=> batchRoute: Use stream to process results instead of paged queries

packages/transition-frontend/src/components/forms/node/TransitNodeCollectionEdit.tsx
fixes #637
Objects need to be in editing mode for changes to be tracked and saved on exit.
=> nodes: set selected nodes collection as editing when editing

packages/chaire-lib-frontend/src/components/pageParts/DistanceUnitFormatter.tsx, packages/chaire-lib-frontend/src/components/pageParts/DurationUnitFormatter.tsx, packages/chaire-lib-frontend/src/components/pageParts/SpeedUnitFormatter.tsx, packages/transition-frontend/src/components/forms/path/TransitPathNodeButton.tsx, packages/transition-frontend/src/components/forms/path/TransitPathStatistics.tsx
The `segments` data attribute may be empty if the path was imported from gtfs. Undefined exceptions were thrown and the interface was blank when deleting nodes from the nodes list.
Also run `yarn format` on the code
=> transitPath: fix nodes list when path has no segments

packages/chaire-lib-frontend/src/components/dashboard/RightPanel.tsx
fixes #791
Available routing modes are fetched asynchronously on the server and sent as props to the panels and forms. The right panel needs to re-compute the contribution elements when that prop value changes so the contribution elements can have the latest value.
=> right panel: Re-compute contributions when routing modes change

packages/transition-backend/src/models/db/migrations/20231206121400_addNodeGeographyIndex.ts
A gist index allows faster queries on the geography field, like returning nodes within a certain distance.
=> db: Add index on the tr_transit_nodes' geography field

packages/transition-backend/jestSetup.ts, packages/transition-backend/src/services/capnpCache/__tests__/dbToCache.test.ts
This makes it easier to mock calls to osrm engine or tr routing in unit tests for example.
The dbToCache test had to be updated because now a event manager exists by default.
=> jest: Add enableAllMocks to transition-backend tests

packages/chaire-lib-common/src/utils/objects/MapObject.ts, packages/chaire-lib-common/src/utils/objects/__tests__/MapObject.test.ts, packages/transition-common/src/services/nodes/__tests__/NodeCollection.test.ts, packages/transition-common/src/services/nodes/__tests__/NodeGeographyUtils.test.ts, packages/transition-common/src/services/odTrip/__tests__/BaseOdTripCollection.test.ts, packages/transition-common/src/services/path/__tests__/PathCollection.test.ts
This method returns true if the geography of the object has changed, otherwise false.
Also add unit tests for the new method and the MapObject class
=> mapObject: add a `hasChangedGeography` method

packages/chaire-lib-common/src/services/events/EventManager.ts, packages/chaire-lib-common/src/services/events/__tests__/EventManager.test.ts, packages/chaire-lib-common/src/test/services/events/EventManagerMock.ts, packages/chaire-lib-common/src/utils/objects/GenericMapObjectCollection.ts, packages/chaire-lib-frontend/src/services/map/MapLayerManager.ts, packages/chaire-lib-frontend/src/services/map/events/GlobalMapEvents.ts, packages/chaire-lib-frontend/src/services/map/events/MapEventsCallbacks.ts, packages/transition-frontend/src/components/forms/accessibilityMap/AccessibilityMapForm.tsx, packages/transition-frontend/src/components/forms/agency/TransitAgencyButton.tsx, packages/transition-frontend/src/components/forms/agency/TransitAgencyEdit.tsx, packages/transition-frontend/src/components/forms/line/TransitLineButton.tsx, packages/transition-frontend/src/components/forms/line/TransitLineEdit.tsx, packages/transition-frontend/src/components/forms/node/TransitNodeEdit.tsx, packages/transition-frontend/src/components/forms/node/TransitNodeImportForm.tsx, packages/transition-frontend/src/components/forms/path/TransitPathButton.tsx, packages/transition-frontend/src/components/forms/path/TransitPathEdit.tsx, packages/transition-frontend/src/components/forms/path/TransitPathImportForm.tsx, packages/transition-frontend/src/components/forms/scenario/TransitScenarioEdit.tsx, packages/transition-frontend/src/components/forms/transitRouting/RoutingResultComponent.tsx, packages/transition-frontend/src/components/forms/transitRouting/TransitRoutingForm.tsx, packages/transition-frontend/src/components/forms/transitRouting/widgets/ODCoordinatesComponent.tsx, packages/transition-frontend/src/components/map/TransitionMainMap.tsx, packages/transition-frontend/src/services/dashboard/LayersAndCollectionsService.ts
* eventManager: Add methods to listen and emit typed events
This allows to use a type for the events, with a `name` and `args` fields for the name of the event and types of arguments in the callback.
The methods are generic, with the generic type being the type of the event. The listening method is `onEvent`, the emitting one is `emitEvent`. It can be called in the code with
`eventManager.emitEvent<MyEventType>('event.myevent', myArgs)`
`eventManager.onEvent<MyEventType>('event.myevent', (myArgs) => void)`
* map: type the `map.updateLayer` event
Use the new `onEvent` and `emitEvent` methods of the EventManager to type the calls to `map.updateLayer`. It receives an argument with 2 fields: `layerName` and `data`, which are respectively the layer to update and the geojson feature collection …
=> Type the event manager and the `map.updateLayer` event

packages/chaire-lib-backend/src/utils/processManagers/OSRMProcessManager.ts
fixes #821
This uses the value set in the mode config's host field even for local servers. This allows to specify a specific URL on which to join the server, for example an ipv4 url where 'localhost' would have resolved to an ipv6 url, or simply a named URL for the local server.
=> osrm: Use the host even for local servers

packages/transition-common/src/services/accessibilityMap/TransitAccessibilityMapCalculator.ts, packages/transition-common/src/services/accessibilityMap/TransitAccessibilityMapRouting.ts, packages/transition-common/src/services/transitRouting/TransitRouting.ts
Fixes #823
For both transit routing and accessibility map, always use the color from the user preferences instead of previous attributes. This allows to update the colors when the preferences are set. Eventually, we may want to be able to change those colors for each calculation from the interface.
=> routing: Take colors from the preferences instead of previous attributes

packages/chaire-lib-common/src/config/osm/overpassQueries/networksPolyForOsrm.ts
We might want to download large data set. Setting an arbitrary timeout prohibit this.
=> Remove timeout for downloading OSM data from Overpass

packages/transition-common/src/services/path/Path.ts, packages/transition-common/src/services/path/__tests__/Path.test.ts, packages/transition-frontend/src/components/forms/path/TransitPathEdit.tsx, packages/transition-frontend/src/services/map/events/PathSectionMapEvents.ts
fixes #835
This adds exhaustive unit tests for the waypoints insert/update/delete and nodes insert/delete operations. It also adds some check of indexes before doing the operation.
After these addition, the coverage of the Path.ts file increased as follows:
% Stmts: 27.16    --> 58.6
% Branch: 34.75  --> 49.7
% Funcs: 33.77    --> 49.33
% Lines: 27.08     --> 58.94
=> path: add tests and documentation for node/waypoint operations

packages/transition-common/src/services/schedules/Schedule.ts, packages/transition-common/src/services/schedules/__tests__/Schedule.test.ts
fixes #846
The period's inbound and outbound path ids are used by Transition to generate periodic schedules, but paths imported from GTFS do not have those fields. It is the trips which really contain the paths used by the schedule.
=> schedules: get associated paths from trips

packages/transition-backend/src/services/gtfsImport/ScheduleImporter.ts, packages/transition-backend/src/services/gtfsImport/__tests__/ScheduleImporter.test.ts
This seems to be currently more intuitive for end users, instead of using the period start/end if the diff between the time and closest trip time is lower than frequency.
Given various issues with schedules (#681, #854, the fact that all trips start at the exact period start, problems inferring frequency with asymetrical trips, to name a few), this sounds like an acceptable compromise.
=> gtfs: Always use custom times when inferring frequencies

packages/transition-common/src/services/path/__tests__/PathData.test.ts, packages/transition-common/src/services/schedules/Schedule.ts, packages/transition-common/src/services/schedules/__tests__/Schedule.test.ts, packages/transition-common/src/services/schedules/__tests__/ScheduleData.test.ts
fixes #844
Add tests for the `generateForPeriod` method with various use cases, with multiple directions/periods. These tests test the actual trip data, not just their numbers.
Make private some methods of the Schedule class. They don't need to be accessible from outside the class.
=> schedules: Add unit tests for schedule generation

Dockerfile, packages/chaire-lib-frontend/package.json, packages/transition-frontend/package.json, yarn.lock
Use the latest compatible version of the `date-fns` package, and use the same for both `transition-frontend` and `chaire-lib-frontend`.
=> dep: Upgrade the `date-fns` package

packages/transition-frontend/src/components/forms/scenario/TransitScenarioEdit.tsx
fixes #880
The exluded/included lines select choices also display the agency acronym next to the line's name, to better identify lines that can have the same name between agencies.
=> scenariosEdit: Add the agency acronym to lines

packages/chaire-lib-backend/src/config/auth/__tests__/localLogin.config.test.ts, packages/chaire-lib-backend/src/config/auth/__tests__/passwordless.config.test.ts, packages/chaire-lib-backend/src/config/auth/index.ts, packages/chaire-lib-backend/src/config/auth/localLogin.config.ts, packages/chaire-lib-backend/src/config/auth/passwordless.config.ts, packages/chaire-lib-backend/src/models/db/__tests__/users.db.test.ts, packages/chaire-lib-backend/src/models/db/migrations/20240313144500_addUserLastLogin.ts, packages/chaire-lib-backend/src/models/db/users.db.queries.ts, packages/chaire-lib-backend/src/services/auth/authModel.ts, packages/chaire-lib-backend/src/services/auth/pwdLessDirectSignupStrategy.ts, packages/chaire-lib-backend/src/services/auth/userAuthModel.ts, packages/chaire-lib-backend/src/services/users/user.ts
fixes #876
* Add a field: `last_login_at` to the users table.
* Add the `recordLogin` method to the UserModel to let the model implement recording login. The default implementation does nothing
* Set the last login time to the user model based on the `users` table
* Call the recordLogin method in passport strategies whenever there are successful logins.
=> users: add a last login time to users

configs/react.tsconfig.json, packages/chaire-lib-common/src/services/objects/CollectionLoadable.ts, packages/chaire-lib-common/src/utils/objects/GenericCollection.ts, packages/transition-backend/src/services/transitObjects/TransitObjectsDataHandler.ts, packages/transition-common/src/services/nodes/__tests__/NodeCollection.test.ts, packages/transition-common/src/services/path/PathCollection.ts, packages/transition-common/src/services/path/__tests__/PathCollection.test.ts
In preparation for #408, here's a few unrelated issues.
Note that the update of the target for react packages is also part of PR #773 where the animated path did not work without.
=> Various small fixes

docs/APIv1/accessibilityMap.yml, packages/transition-backend/src/api/public/AccessibilityMapAPIResponse.ts
The `durationSeconds` and `areaSqM` parameters have been added to the accessibility map GeoJSON in the /api/v1/accessibility endpoint response. The `durationSeconds` parameter especially is necessary to differentiate between the travel time represented by each polygon generated in the response. Also, the QGIS plugin needs this information to differentiate between the polygons.
=> Public API: Added important GeoJSON parameters to accessibility map polygon

packages/chaire-lib-frontend/src/services/auth/__tests__/verifyAuthentication.test.ts, packages/chaire-lib-frontend/src/services/auth/verifyAuthentication.ts, packages/transition-frontend/src/app-transition.tsx
This allows other code path to re-use the app loading code to verify authentication. One example is when the user is logged out, the requests will typically return a 401 response to the application. The code handling this response code can request the server to verifyAuthentication and thus differentiate between a logged out user and one trying to access a forbidden resource.
=> frontend: Extract the `verifyAuthentication` method

.github/workflows/transition.yml
Old version were deprecated, see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Upgrade github actions in main workflow

packages/chaire-lib-backend/src/services/auth/userEmailNotifications.ts
Sending email is often done asynchronously by the server and there is nothing to catch the error in the sendEmail promise. All email sending functions now catch and log the exception before throwing it back.
=> userEmail: Add try/catch around email sending functions

packages/transition-backend/src/api/public/AccessibilityMapAPIResponse.ts, packages/transition-backend/src/services/capnpCache/__tests__/dbToCache.test.ts, packages/transition-backend/src/services/capnpCache/dbToCache.ts, packages/transition-backend/src/services/nodes/NodeCollectionUtils.ts, packages/transition-backend/src/services/nodes/__tests__/NodeCollectionUtils.test.ts, packages/transition-backend/src/socketServerApp.ts
We now save the transferable nodes in the database, so we don't really need to recalculate them at each startup. But we still need to save them to the capnp cache file.
We add a saveAllNodesToCache function to NodeCollectionUtils, based on saveAndUpdateAllNodes, that only store the node data without recalculating it. We add a else in the recreateCache function where we test for the refreshTransferrableNodes flag to call our new function in that case. (That way we always save the transferable nodes to cache)
The dbToCache were missing a mockClear, we switch it to jest.clearAllMocks() and fixes the erroneous tests
The call in socketServerApp was changed to ask for not refreshing the transferable node when recreating the cache on startup
=> Don't recalculate transferable nodes on startup

packages/transition-backend/src/models/db/__tests__/transitNodes.db.test.ts, packages/transition-backend/src/models/db/transitNodes.db.queries.ts, packages/transition-backend/src/services/gtfsImport/StopImporter.ts, packages/transition-backend/src/services/gtfsImport/__tests__/StopImporter.test.ts, packages/transition-backend/src/services/nodes/NodeCollectionUtils.ts, packages/transition-backend/src/services/nodes/TransferableNodeUtils.ts, packages/transition-backend/src/services/nodes/TransitNode.ts, packages/transition-backend/src/services/nodes/__tests__/NodeCollectionUtils.test.ts, packages/transition-backend/src/services/nodes/__tests__/TransferableNodeUtils.test.ts, packages/transition-backend/src/services/nodes/__tests__/TransitNode.test.ts
fixes #908
Since KDBush sometimes does not return a node which is at the exact
location as another one, the main code path sometimes created new nodes
at the exact same location when the aggregation radius was set to 0.
postgis, on the other hand, does not do that, so we get the existing
node from the database in that case.
Also
* Move `getNodesInBirdDistance` to `NodeCollecitonUtils`
* Add a db and utils functions to get nodes withing distance of a point (one already existed for existing nodes)
* Run `yarn format` on the code
=> GTFS: Use postgis to get existing nodes when aggregation radius is 0

packages/chaire-lib-backend/src/models/db/__tests__/tokens.db.test.ts, packages/chaire-lib-backend/src/models/db/dataSources.db.queries.ts, packages/chaire-lib-backend/src/models/db/default.db.queries.ts, packages/chaire-lib-backend/src/models/db/zones.db.queries.ts, packages/transition-backend/package.json, packages/transition-backend/src/models/db/__mocks__/transitPaths.db.queries.ts, packages/transition-backend/src/models/db/__tests__/TransitPath.db.test.ts, packages/transition-backend/src/models/db/__tests__/TransitSchedule.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitAgencies.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitLines.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitNodes.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitScenarios.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitServices.db.test.ts, packages/transition-backend/src/models/db/migrations/20240503162600_addUniqueScenarioServiceIdx.ts, packages/transition-backend/src/models/db/odPairs.db.queries.ts, packages/transition-backend/src/models/db/places.db.queries.ts, packages/transition-backend/src/models/db/simulationRuns.db.queries.ts, packages/transition-backend/src/models/db/simulations.db.queries.ts, packages/transition-backend/src/models/db/transitAgencies.db.queries.ts, packages/transition-backend/src/models/db/transitLines.db.queries.ts, packages/transition-backend/src/models/db/transitNodes.db.queries.ts, packages/transition-backend/src/models/db/transitPaths.db.queries.ts, packages/transition-backend/src/models/db/transitScenarios.db.queries.ts, packages/transition-backend/src/models/db/transitSchedules.db.queries.ts, packages/transition-backend/src/models/db/transitServices.db.queries.ts, packages/transition-backend/src/services/gtfsImport/ScheduleImporter.ts
Also make sure individual operations that span many tables (like scenarios and schedules) are all inside transactions to avoid errors while saving those object to leave the object is an intermediate, unknown, state.
While doing so, to make transactions as fast and short as possible, the queries that involved reading/processing/writing now try to do it in a single database query, or favor batch inserts/updates/deletes.
=> db: Allow all queries to receive a transaction parameter

packages/chaire-lib-frontend/src/components/pageParts/Header.tsx
This is useful to fine tune the style of the title.
Also, in Evolution's `playwright` tests, it should be possible to easily identify this div.
=> header: Add ID to the header title div

packages/chaire-lib-backend/src/models/db/types.db.ts, packages/transition-backend/src/api/__tests__/transitObjects.socketRoutes.test.ts, packages/transition-backend/src/api/transitObjects.socketRoutes.ts, packages/transition-backend/src/models/db/__tests__/transitServices.db.test.ts, packages/transition-backend/src/models/db/transitServices.db.queries.ts, packages/transition-backend/src/services/gtfsImport/ServiceImporter.ts, packages/transition-backend/src/services/gtfsImport/__tests__/ServiceImporter.test.ts, packages/transition-backend/src/services/transitObjects/transitServices/ServiceDuplicator.ts, packages/transition-backend/src/services/transitObjects/transitServices/ServiceUtils.ts, packages/transition-backend/src/services/transitObjects/transitServices/__tests__/ServiceDuplicator.test.ts, packages/transition-backend/src/services/transitObjects/transitServices/__tests__/ServiceUtils.test.ts, packages/transition-common/src/services/service/ServiceDuplicator.ts, packages/transition-common/src/services/service/ServiceUtils.ts, packages/transition-frontend/src/components/forms/service/TransitServiceButton.tsx
First and easiest step towards #297, but it prepares the approach:
* Add argument to database `collection` function to fetch partial collection of services
* Add database queries to fetch all services names starting with a certain prefix, to generate unique names
* Add operations to duplicate single or multiple services, with separate function for saving, which allow longer running duplicate operations (like agency or line duplication), to postpone saving when all objects are ready to reduce the transaction time.
* Add socket route to duplicate services
* Let the service duplication button use this new socket route to duplicate the service. Other callers, like line duplicator are not ready yet to call the new socket route. They will themselves be moved to backend later.
=> Bring the service duplication operation server side 

pyTransition/pyTransition/transition.py, pyTransition/tests/test_transition.py
We add a normalize_url function that remove extra characters from an URL and also add build_url function so that we don't manipulate URL as string everywhere
Add a test with an extra "/" at the end of the base URL
Created with the help of chatgpt
=> Use urllib functions to normalize URL

packages/chaire-lib-common/src/services/geodata/GeoJSONUtils.ts, packages/chaire-lib-common/src/services/geodata/__tests__/GeoJSONUtils.test.ts
This function takes any geojson object and will return the coordinates if it is a Point, a Point feature or a feature collection with only one Point feature. Otherwise, it returns undefined.
Also add tests for the GeoJSONUtils functions.
=> geoJSON utils: Add a `getPointCoordinates` function

packages/chaire-lib-backend/src/models/db/__tests__/tokens.db.test.ts, packages/chaire-lib-backend/src/models/db/migrations/20240531103600_addTokenUpdatedAt.ts, packages/chaire-lib-backend/src/models/db/tokens.db.queries.ts, packages/chaire-lib-backend/src/services/auth/token.ts
The table was built with the `onUpdateTrigger` constraint, but the updated_at field is not present, so it is not possible to update the table. Also rename `creation_date` to `created_at` to match other tables.
=> db: Add the updated_at field to the tokens table

packages/chaire-lib-common/package.json, packages/chaire-lib-common/src/utils/ParamsValidatorUtils.ts, packages/chaire-lib-common/src/utils/__tests__/ParamsValidatorUtils.test.ts, yarn.lock
This will allow to validate the [socket] route parameters more easily and return corresponding errors.
=> Move the ParamValidatorUtils from evolution to chaire-lib

packages/chaire-lib-common/src/services/routing/RoutingResult.ts, packages/chaire-lib-common/src/services/routing/TransitRoutingResult.ts, packages/chaire-lib-common/src/services/routing/__tests__/RoutingResult.test.ts, packages/chaire-lib-common/src/services/routing/__tests__/TransitRoutingResult.test.ts, packages/transition-backend/src/models/db/__tests__/batchRouteResults.db.test.ts, packages/transition-backend/src/models/db/batchRouteResults.db.queries.ts, packages/transition-backend/src/services/routingCalculation/RoutingCalculator.ts, packages/transition-backend/src/services/transitRouting/TrRoutingBatchResult.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrRoutingBatch.test.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrRoutingBatchResult.test.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrRoutingOdTrip.test.ts, packages/transition-common/src/services/transitRouting/TransitRoutingCalculator.ts, packages/transition-common/src/services/transitRouting/TransitRoutingResult.ts, packages/transition-common/src/services/transitRouting/__tests__/TransitRoutingCalculator.test.ts, packages/transition-common/src/services/transitRouting/__tests__/TransitRoutingResult.test.ts, packages/transition-frontend/src/components/forms/transitRouting/RoutingResultComponent.tsx, packages/transition-frontend/src/components/forms/transitRouting/TransitRoutingResultComponent.tsx
This commit is part of work to move the routing calculations to chaire-lib instead of Transition, so that other tools can benefit from it (#954).
The main result interface is called `RoutingResult`. 2 classes implement it `UnimodalRoutingResult` and `TransitRoutingResult`. There is no need to call the `getWalkOnlyRoute` method anymore (it has been removed), as it is not part of the interface and required custom code. Rather, the `getPath` method will return either a Route or TrRoutingRoute in the `TransitRoutingResult` class.
Tests have been added for the results class. `TransitRoutingResult` required to be split between the common chaire-lib part (the class itself) and the transition part (requiring a PathCollection to get the geojson from transition paths). A parameter allows to specify …
=> Move RoutingResult classes to chaire-lib, add tests and use common interface

packages/transition-frontend/src/components/forms/preferences/sections/PreferencesSectionGeneral.tsx, packages/transition-frontend/src/components/map/layers/AnimatedArrowPathLayer.tsx, packages/transition-frontend/src/components/map/layers/TransitionMapLayer.tsx, packages/transition-frontend/src/config/layers.config.ts
fixes #974
The `maxRadiusPixels` and `minRadiusPixels` can be set in the layer
description to prevent the points from getting too big/small when
zooming in/out. If the property is a number, the lineWidth min/max
pixels are also set to 1/3 of the corresponding radius.
Here's how it looks now (@kaligrafy 10 review points if you find where this image shows :p ):
=> deck.gl: Support the max/minRadiusPixels properties

packages/chaire-lib-common/src/utils/ParamsValidatorUtils.ts, packages/chaire-lib-common/src/utils/__tests__/ParamsValidatorUtils.test.ts
These functions validation whether the parameter is an integer or a number, whether positive, zero or negative.
=> paramValidatorUtils: Add `isInteger` and `isNumber` functions

.env.example, packages/chaire-lib-backend/src/services/mailer/transport.ts
This add the necessary config to let nodemailer add a DKIM signature to sent email
We need 3 news environment variables:
MAIL_TRANSPORT_DKIM_SELECTOR (Select which DKIM key to use) MAIL_TRANSPORT_DKIM_DOMAIN (Domain to select the key from) MAIL_TRANSPORT_DKIM_PRIVATE_PATH (File path to the DKIM private key)
=> Add support to enable DKIM signature in email sending

packages/transition-backend/src/socketServerApp.ts
fixes #991
The latest socket.io upgrade set the upload size default to 1MB. We set it back to 100MB since Transition users often have to upload large files for calculations.
=> socket: Set the `maxHttpBufferSize` when initializing socket

packages/transition-backend/src/api/public/NodesAPIResponse.ts, packages/transition-backend/src/api/public/__tests__/NodesAPIResponse.test.ts
fixes #990
Nodes that are not imported from gtfs may not have the `stops` data property defined. It is not mandatory anyway, so we should not expect it to exist.
Also add unit tests for the NodesAPIResponse class.
=> api: fix `/api/v1/nodes` when stops are undefined

packages/transition-frontend/package.json, packages/transition-frontend/webpack.config.js, yarn.lock
These are the latest working versions with webpack 4 that do not require any changes to the webpack config.
* webpack: 4.43.0 => 4.47.0
* style-loader: 1.2.1 => 2.0.0
* sass-loader: 9.0.2 => 9.0.3
* mini-css-extract-plugin: 0.9.0 => 1.6.2
* clean-webpack-plugin: 3.0.0 => 4.0.0
* compression-webpack-plugin: 4.0.0 => 5.0.2
=> dep: Upgrade webpack 4 to latest

packages/transition-backend/package.json, packages/transition-backend/src/serverApp.ts, yarn.lock
* request-ip: 2.1.3 => 3.3.0
This removes dependency to is_js, which has a vulnerability issue.
=> dep: upgrade version of `request-ip`

packages/transition-backend/src/services/executableJob/ExecutableJob.ts, packages/transition-backend/src/services/executableJob/JobCheckpointTracker.ts, packages/transition-backend/src/tasks/TransitionWorkerPool.ts
This will help debug an issue where when the job restarts after theoretically 60% of the calculations have been done, the job still restarts at around 10%.
This commit can be reverted once the problem is solved.
=> batchRouting: Add logging around the checkpoints

.github/workflows/transition.yml, packages/chaire-lib-backend/src/utils/osrm/__tests__/OSRMMode.test.ts
Node 20 is the current LTS, we should migrate our builds to it
(Copied and updated from https://github.com/chairemobilite/transition/pull/1000)
=> Enable build on Node 20.x in github workflow

packages/transition-backend/src/services/transitRouting/TrRoutingBatch.ts
Tentatively trying to investigate issue #1011 on instances. This will allow to see if the checkpoint handling caused issues, as the problem seems to come from "old" trip queries, ie that should have long been handled.
This commit can be reverted once the issue is solved
=> debug: Add logging before/after handling batch routing trip

packages/chaire-lib-backend/src/services/routing/Routing.ts, packages/chaire-lib-backend/src/utils/trRouting/TrRoutingServiceBackend.ts, packages/transition-backend/src/services/transitRouting/TrRoutingBatch.ts, packages/transition-backend/src/services/transitRouting/TrRoutingOdTrip.ts
To investigate issue #1011 on instances, we add logs before and after
the calculation functions, each individual mode calculation and the
trRouting requests. The log messages include the origin/destination
coordinates to allow to track individual queries. These can be matched
with the odTripIndex from a log message in the batch routing task.
=> debug: Add loggin before/after various routing functions

packages/chaire-lib-common/src/services/trRouting/TrRoutingService.ts, packages/transition-backend/src/api/services.socketRoutes.ts
While investigating #1011, we add logging in the trRouting's socket calls, to see if the callback is called by the server and received by teh caller.
=> debug: Add logging before/after transit route's socket calls

Dockerfile, packages/chaire-lib-backend/package.json, packages/chaire-lib-common/package.json, packages/transition-common/package.json, yarn.lock
Also upgrade node-fetch version to latest 2.x
=> Use Node 20 for Docker builds

docs/APIv1/API.yml, packages/transition-backend/src/api/__tests__/public.routes.test.ts, packages/transition-backend/src/api/public.routes.ts
This API should mirror the `route` API, which is also a POST. While they could be GET API, as the same parameters expect to return the same data and it does not trigger any data update in the system, the fact that they pass geojson features makes it easier to use a POST request. For a GET, ideally, only the coordinates should be returned.
=> API: Change `summary` endpoint from GET to POST

packages/transition-backend/package.json, packages/transition-backend/src/api/__tests__/services.socketRoutes.test.ts, packages/transition-backend/src/api/public.routes.ts, packages/transition-backend/src/api/services.socketRoutes.ts, packages/transition-backend/src/services/accessibilityMap/TransitAccessibilityMapCalculator.ts, packages/transition-backend/src/services/accessibilityMap/__tests__/TransitAccessibilityMapCalculator.test.ts, packages/transition-backend/src/services/routingCalculation/RoutingCalculator.ts, packages/transition-backend/src/services/routingCalculation/__tests__/RoutingCalculator.test.ts, packages/transition-backend/src/services/simulation/methods/AccessibilityMapSimulation.ts, packages/transition-backend/src/services/transitRouting/TrAccessibilityMapBatch.ts, packages/transition-backend/src/services/transitRouting/__tests__/TrAccessibilityMapBatch.test.ts, packages/transition-common/package.json, packages/transition-common/src/services/accessibilityMap/types.ts, packages/transition-frontend/src/components/forms/accessibilityMap/AccessibilityMapForm.tsx, packages/transition-frontend/src/services/routing/RoutingUtils.ts, packages/transition-frontend/src/services/routing/__tests__/RoutingUtils.test.ts
The main accessibility map calculation function is now moved to the backend instead of the common package.
This adds a socket route `accessibilityMap.calculateWithPolygons` to let the frontend have access to the calculation with polygon.
This will lead to later PRs removing the TrRoutingServiceManager, which is only used in the accessibility map calculations.
=> accessibilityMap: Bring the calculation to the backend

packages/chaire-lib-backend/src/utils/trRouting/TrRoutingServiceBackend.ts
reverts changes done in this file in https://github.com/tahini/transition/commit/657976c2b9e1d3a828514125a28d4c89e4fc989f
This log statements were wrongly placed as the request is a promise and the log happened before awaiting for the promise completion.
Also, with the TransitRoutingService in the backend, this log is not necessary anymore, as the caller already has log statements.
=> debug: Remove log statements from `TrRoutingServiceBackend`'s route

examples/config.js, packages/chaire-lib-backend/src/config/ServerConfig.ts, packages/chaire-lib-backend/src/config/__tests__/ServerConfig.test.ts, packages/chaire-lib-backend/src/config/__tests__/server.config.test.ts, packages/chaire-lib-backend/src/config/auth/__tests__/directToken.config.test.ts, packages/chaire-lib-backend/src/config/auth/directToken.config.ts, packages/chaire-lib-backend/src/config/auth/index.ts, packages/chaire-lib-backend/src/config/server.config.ts, packages/chaire-lib-backend/src/utils/processManagers/TrRoutingProcessManager.ts, packages/chaire-lib-backend/src/utils/processManagers/__tests__/TrRoutingProcessManager.test.ts, packages/chaire-lib-backend/src/utils/trRouting/TrRoutingServiceBackend.ts, packages/chaire-lib-common/src/api/TrRouting/index.ts, packages/chaire-lib-common/src/config/defaultPreferences.config.ts, packages/chaire-lib-common/src/config/shared/__tests__/project.config.test.ts, packages/chaire-lib-common/src/config/shared/project.config.ts, packages/transition-backend/src/api/services.socketRoutes.ts, packages/transition-backend/src/services/simulation/SimulationRun.ts
This adds the `trRouting` property to the config type. This property contains data for the `single` instance for individual calculations (UI and public API) and `batch` instance (for tasks). For each instance, the `port` and `cacheAllScenarios` properties can be set.
The configuration objects replace the `trRouting` preference that contained the `port` and `batchPortStart` and the current `trRoutingCacheAllScenarios` configuration option.
Port management when starting or querying trRouting is updated to match the new configuration options.
=> trRouting: Move port and cacheAllScenarios to instance specific config

examples/config.js, packages/chaire-lib-backend/package.json, packages/chaire-lib-backend/src/config/__tests__/ServerConfig.test.ts, packages/chaire-lib-backend/src/config/__tests__/server.config.test.ts, packages/chaire-lib-backend/src/config/server.config.ts, packages/chaire-lib-backend/src/utils/processManagers/OSRMProcessManager.ts, packages/chaire-lib-backend/src/utils/processManagers/ProcessManager.ts, packages/chaire-lib-backend/src/utils/processManagers/TrRoutingProcessManager.ts, packages/chaire-lib-backend/src/utils/processManagers/__tests__/ProcessManager.test.ts, packages/chaire-lib-backend/src/utils/processManagers/__tests__/TrRoutingProcessManager.test.ts, packages/transition-backend/src/services/simulation/SimulationRun.ts, packages/transition-frontend/webpack.config.js, yarn.lock
* Use named objects instead of ordinal parameters for the numerous function parameters. This makes a call more readable, make it easier to fine-tune specific parameters while keeping the default values for others, and will make adding yet more parameters simpler.
* Let `ProcessManager` support log file count and size as extra parameter
* Let `TrRoutingProcessManager` support log file count and size as extra parameter. `startBatch` now also supports the `debug` option.
* Add tests for the new functionalities
=> Allow the process manager to configure log files count and sizes

docs/APIv1/route.yml, packages/chaire-lib-common/src/utils/TrError.ts, packages/transition-backend/src/api/public/RouteAPIResponse.ts, pyTransition/README.md
In case of a server error while executing a /route request, the error info will be included in the response. Updates the API doc with the new info.
Also removes a deprecated field from an error handling function. 
Also fixes some incorrect function names in the pyTransition readme.
Fix: #1043
Example:
=> Add server side errors to /route API request response.

packages/transition-backend/src/services/transitRouting/TrRoutingBatch.ts, packages/transition-backend/src/tasks/TransitionWorkerPool.ts
fixes #710
* Cancelled jobs sometimes were not really cancelled if a checkpoint was set after the job status was set to cancelled in the main thread, but before the automatic task refresh every 5 seconds, so we refresh the task before updating it in the checkpoint update.
* Also, refreshing and saving the job would throw an error if the job is deleted from the DB and would kill the running thread, which would cause the trRouting process to be left defunct. So we add a catch when refreshing/updating the job and stopping the trRouting process is done in the finally block, to make sure it is always stopped, even in case of an exception.
=> batchRoute: Better handle job cancellation and deletion

locales/en/transit.json, locales/fr/transit.json, packages/transition-backend/file/definitions/README.md, packages/transition-backend/file/definitions/definitions-en.tex, packages/transition-backend/file/definitions/definitions-fr.tex, packages/transition-backend/package.json, packages/transition-backend/src/api/all.socketRoutes.ts, packages/transition-backend/src/api/definitions.socketRoutes.ts, packages/transition-backend/src/services/documentation/Definitions.ts, packages/transition-backend/src/services/documentation/__tests__/Definitions.test.ts, packages/transition-frontend/package.json, packages/transition-frontend/src/components/dashboard/TransitionRightPanel.tsx, packages/transition-frontend/src/components/forms/agency/TransitAgencyButton.tsx, packages/transition-frontend/src/components/forms/agency/TransitAgencyList.tsx, packages/transition-frontend/src/components/forms/node/TransitNodePanel.tsx, packages/transition-frontend/src/components/forms/path/TransitPathButton.tsx, packages/transition-frontend/src/components/forms/path/TransitPathList.tsx, packages/transition-frontend/src/components/parts/DocumentationTooltip.tsx, packages/transition-frontend/src/services/definitions/DefinitionsService.ts, yarn.lock
Add Latex documentation to the server, and send definitions to the client that can then be displayed when clicking on specific symbols thanks to a new React tooltip component.
Adds this tooltip to Agencies, Lines, Paths, half cycle time, and Stop Nodes.
Fix: #136 
Examples:
=> Add documentation popups

.github/workflows/latex.yml
To insure that the latex file are not corrupted, let's build them in the CI
Closes: #1111
=> Build latex definition in CI

packages/transition-frontend/src/components/parts/DocumentationTooltip.tsx, packages/transition-frontend/src/services/definitions/DefinitionsService.ts, packages/transition-frontend/src/services/definitions/__tests__/DefinitionService.test.ts
The `DocumentationTooltip` component now requests the definition only if the user clicks to display the tooltip. The loader is shown while it is loading.
The `DefinitionService` caches the results from previous server calls, such that it is loaded only once. If a specific definition request is ongoing, it does not call the server again but waits for the server to return a value or error. Upon error, the next call to get the definition will try to get it again.
Add unit tests for the `getDefinitionFromServer` function
=> doc tooltip: Fetch on demand and cache definition results

packages/transition-backend/src/models/db/__tests__/transitNodes.db.test.ts, packages/transition-backend/src/models/db/transitNodes.db.queries.ts
This improves the time and memory necessary to retrieve the node geojson collection and it does not appear to have side effects.
On a large instance (all the greater Montreal area) this divides by 3 the query time to get the node geojson collection and can reduce the memory usage in the browser by 100 MB.
Tested in the UI:
* Node edits
* Multiple node edits
* Path creation and routing
=> nodes: remove the `data` field from geojson collection

examples/config.js, packages/chaire-lib-backend/src/config/ServerConfig.ts, packages/chaire-lib-backend/src/config/__tests__/ServerConfig.test.ts, packages/chaire-lib-backend/src/config/__tests__/server.config.test.ts, packages/chaire-lib-backend/src/config/server.config.ts, packages/chaire-lib-backend/src/utils/processManagers/OSRMProcessManager.ts, packages/chaire-lib-backend/src/utils/processManagers/OSRMServicePath.ts, packages/chaire-lib-backend/src/utils/processManagers/__tests__/OSRMProcessManager.test.ts, packages/chaire-lib-common/src/config/__tests__/Preferences.test.ts, packages/chaire-lib-common/src/config/defaultPreferences.config.ts, packages/chaire-lib-common/src/services/routing/OSRMRoutingService.ts, tests/config_test.js
Migrate OSRM settings from the defaultPreferences.config.ts file in chaire-lib-common to server.config,ts file in chaire-lib-backend
Also adds some todos as a reminder to rework some settings that can't be moved at the moment.
Fix: #1084
=> Migrate OSRM settings

packages/transition-common/src/services/accessibilityMap/TransitAccessibilityMapResult.ts
Now that the NodeCollection does not return the 'data' field, when nodes are retrieved from this collection, the data field will be undefined, so we make sure to undefined-check it before trying to read accessiblePlaces data.
=> accessibility map: check that data is defined for accessiblePlaces

packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/cycling.lua
In general the OSM community do not encourage the use for this tag, but it can be a good indication of dangerous bike routes. (We have a few street marked as such in Montreal)
This add a penalty to routing on those segments.
This was tested on De La Verandrye street, after setting the secondary default weight to 0.9 to have OSRM first route on it. After adding this code with the 0.9 weight, we see that the road is avoided.
=> Add a weight for bicycle=discouraged tag in OSRM profile

packages/chaire-lib-backend/jest.config.js, packages/chaire-lib-backend/jest.sequential.config.js, packages/chaire-lib-backend/src/api/admin.routes.ts, packages/chaire-lib-backend/src/api/auth.routes.ts, packages/chaire-lib-backend/src/api/routing.socketRoutes.ts, packages/chaire-lib-backend/src/api/trRouting.routes.ts, packages/chaire-lib-backend/src/config/server.config.ts, packages/chaire-lib-backend/src/scripts/database/token-cleanup.task.ts, packages/chaire-lib-backend/src/services/auth/anonymousLoginStrategy.ts, packages/chaire-lib-backend/src/services/auth/authModel.ts, packages/chaire-lib-backend/src/services/files/SocketFileUploader.ts, packages/chaire-lib-backend/src/services/prompt/CliPromptGeojsonPolygonService.ts, packages/chaire-lib-backend/src/services/routing/Routing.ts, packages/chaire-lib-backend/src/services/users/users.ts, packages/chaire-lib-backend/src/tasks/user/createUser.ts, packages/chaire-lib-backend/src/utils/osrm/OSRMService.ts, packages/chaire-lib-backend/src/utils/processManagers/OSRMProcessManager.ts, packages/chaire-lib-backend/src/utils/processManagers/OSRMServicePreparation.ts, packages/chaire-lib-backend/src/utils/trRouting/TrRoutingServiceBackend.ts
Removed lint warnings from the chaire-lib-backend package, except for "unexpected type any" and require() related ones.
30 warnings got removed (152 to 122)
=> Remove Lint warnings from chaire-lib-backend

packages/chaire-lib-backend/src/models/db/default.db.queries.ts, packages/transition-backend/src/models/capnpCache/transitLines.cache.queries.ts, packages/transition-backend/src/models/db/__tests__/TransitPath.db.test.ts, packages/transition-backend/src/models/db/__tests__/TransitSchedule.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitLines.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitServices.db.test.ts, packages/transition-backend/src/models/db/migrations/20241003145700_useNumericIdsInSchedulesTables.ts, packages/transition-backend/src/models/db/transitPaths.db.queries.ts, packages/transition-backend/src/models/db/transitSchedules.db.queries.ts, packages/transition-backend/src/services/evolutionaryAlgorithm/preparation/ServicePreparation.ts, packages/transition-backend/src/services/gtfsExport/__tests__/ScheduleExporter.test.ts, packages/transition-backend/src/services/gtfsImport/ScheduleImporter.ts, packages/transition-backend/src/services/gtfsImport/__tests__/ScheduleImporter.test.ts, packages/transition-common/src/services/schedules/Schedule.ts, packages/transition-common/src/services/schedules/ScheduleDuplicator.ts, packages/transition-common/src/services/schedules/__tests__/Schedule.test.ts, packages/transition-common/src/services/schedules/__tests__/ScheduleData.test.ts, packages/transition-common/src/services/schedules/__tests__/ScheduleDuplicator.test.ts
Change the schedule, schedule_periods and schedule_period_trips's
primary id columns from uuid to auto-increment numeric IDs. The old
uuid is kept is a column called `uuid`. The foreign keys are modified
to use the numeric key instead. The `schedule_id` column of the trips'
table is removed, as there is already a schedule_period_id foreign which
has a foreign key to the schedule_id. Having both in trips open the door
to data integrity issues where the period could not belong to the same
schedule as the trip.
auto-increment numeric IDs are more performant than uuids as keys. It
will also allow to more easily duplicate multiple elements in a table
with predictable sort order, that uuids do not allow.
This commit only changes the database table queries. The Schedule class
still use the uuid …
=> schedules: Use numeric ids for schedules tables primary keys

locales/en/main.json, locales/en/transit.json, locales/fr/main.json, locales/fr/transit.json, packages/transition-common/src/services/accessibilityMap/TransitAccessibilityMapRouting.ts, packages/transition-frontend/src/components/forms/accessibilityMap/AccessibilityMapForm.tsx
fix: #1063 
Remove the maximum duration for accessibilityMap
=> Remove the maximum duration for accessibilityMap

packages/transition-backend/src/models/db/__tests__/transitNodes.db.test.ts, packages/transition-backend/src/models/db/transitNodes.db.queries.ts, packages/transition-common/src/services/accessibilityMap/TransitAccessibilityMapResult.ts
The `data` field is mandatory in the `NodesAttributes`, but it was just dropped from the geojson collection. We instead return an empty object for data, to make sure it exists.
=> nodes db: return an empty data field for the geojson collection

.github/workflows/readme.yml, pyTransition/README.md, pyTransition/code-to-readme.py, pyTransition/examples/README.md, pyTransition/examples/accessibility_map.py, pyTransition/examples/basic_usage.py, pyTransition/examples/basic_usage_token.py, pyTransition/examples/routing.py, pyTransition/examples/test_credentials.py, pyTransition/readme-examples-config.yaml
We add a python script (code-to-readme.py, created by Claude.AI) which will replace marked script sections with actual content of scripts.
This is driven by a configuration files, readme-examples-config.yaml which define name of script file and section of the script to extract.
We need to run the following to update the README file: python3 code-to-readme.py --readme README.md --config readme-examples-config.yaml
Documentation about this script usage and the config file format is in the script header
We extracted 4 scripts from the previous README and put them in the examples directory. Some fixes were applied, but part of the scripts are still broken, we will fix in further commit.
=> Rework pyTransition README to integrate actual example scripts

packages/chaire-lib-frontend/jest.config.js, packages/chaire-lib-frontend/src/components/forms/auth/localLogin/CaptchaComponent.tsx, packages/chaire-lib-frontend/src/components/input/DayRange.tsx, packages/chaire-lib-frontend/src/components/input/InputCheckbox.tsx, packages/chaire-lib-frontend/src/components/input/InputStringFormatted.tsx, packages/chaire-lib-frontend/src/components/pageParts/SelectedObjectButtons.tsx, packages/chaire-lib-frontend/src/components/pageParts/admin/users/TableFilters.tsx, packages/chaire-lib-frontend/src/components/pageParts/admin/users/UsersComponent.tsx, packages/chaire-lib-frontend/src/components/pageParts/admin/users/react-table-config.d.ts, packages/chaire-lib-frontend/src/components/pages/ForgotPasswordPage.tsx, packages/chaire-lib-frontend/src/components/pages/LoadingPage.tsx, packages/chaire-lib-frontend/src/components/pages/LoginPage.tsx, packages/chaire-lib-frontend/src/components/pages/ResetPasswordPage.tsx, packages/chaire-lib-frontend/src/components/routers/PrivateRoute.tsx, packages/chaire-lib-frontend/src/components/routers/PublicRoute.tsx, packages/chaire-lib-frontend/src/services/map/events/GlobalMapEvents.ts
The lint warnings from chaire-lib-frontend (other than "unexpected any") have been removed.
29 warnings got removed (122 to 93).
=> Remove Lint warnings from chaire-lib-frontend

docs/README.md, pyTransition/README.md
Add a readme in the `docs` folder, with links to the transition's public API documentation and Transition tutorial.
Fix the link in `pyTransition` to go to the right doc page.
=> docs: Add link to Transition public API documentation

packages/transition-frontend/src/components/forms/path/TransitPathEdit.tsx
fixes #1178
The upgrade to React 19 seemingly changed the handling of events in such a way that the path selection event is now handled before the `TransitPathEdit` component is mounted, while it was handled after in the React 16 version. So we call the `updateLayers` method at mount to display the selected path.
=> paths: update layers when TransitPathEdit component is mounted

packages/chaire-lib-common/src/tasks/dataImport/OsmDataPreparationNonResidential.ts, packages/chaire-lib-common/src/tasks/dataImport/OsmDataPreparationResidential.ts, packages/chaire-lib-common/src/tasks/dataImport/data/__tests__/osmGeojsonService.test.ts, packages/chaire-lib-common/src/tasks/dataImport/data/dataGeojson.ts, packages/chaire-lib-common/src/tasks/dataImport/data/dataOsmRaw.ts, packages/chaire-lib-common/src/tasks/dataImport/data/osmGeojsonService.ts, packages/chaire-lib-common/src/tasks/dataImport/prepareOsmDataForImport.ts
Change the import and process osm data task so that it reads the source files with an asynchronous stream. Also adds an option in one of the functions used by the task so that it will not halt if just one geojson is missing compared to the raw OSM data.
=> Streamify import and process osm data task

packages/chaire-lib-common/src/tasks/dataImport/enhanceAndSaveOsmPolygonData.ts
Change the enhance polygon task so that it will read its source files with an asynchronous stream, allowing it to work on large files. It also fixes a bug where the levels of buildings was always set to 1. Now, the level is only set to 1 if it does not already exist, and the levels:imputed attributed is marked as true in that case.
=> Fix enhance polygon task 

packages/chaire-lib-frontend/src/store/auth/__tests__/reducer.test.ts, packages/chaire-lib-frontend/src/store/auth/reducer.ts
The `AuthAction` type is defined in the `types` file and does not need to be re-declared in the reducer. This double declaration causes compilation errors in packages using it.
=> auth: remove redundant AuthAction type declaration

packages/chaire-lib-frontend/src/components/pages/admin/UsersPage.tsx
This page caused errors, with an invalid hook call to useNavigate in a constructor. We convert the page to a function component instead.
=> users: fix `UsersPage` component with new React

README.md
The 7b55bee commit has renamed the `docs/setupDevEnvironmentUbuntu20.04.md` file into `docs/setupDevEnvironmentUbuntu.md`. Unfortunately the link in the README file was pointing to the previous version.
The current commit replaces the old link with the new one.
--- 
By the way (and not in the commit message), I love your project ;)
=> readme: Update broken link

packages/transition-backend/src/models/db/migrations/20250212104000_schedulePeriodOnDeleteSetNull.ts, packages/transition-backend/src/services/transitObjects/TransitObjectsDataHandler.ts, packages/transition-common/src/services/path/Path.ts
fixes #1237 
Add a "set null" contraints on the schedule period's outbound_path_id and inbound_path_id to avoid deleting all trips if one of the path is deleted.
Refresh a line's schedule after deleting a path
Read the object from database after saving it.
=> path: fix schedule update on line when a path is deleted

packages/chaire-lib-backend/src/api/auth.routes.ts, packages/chaire-lib-backend/src/config/auth/index.ts, packages/chaire-lib-common/src/config/shared/project.config.ts
These options are optional boolean options added to the `auth` object of the project.config's file.
Also hide the corresponding routes and auth methods conditional to the enablement of those methods instead of being available all the time.
Display an error message if one of those auth method is enabled but the required environment variables are not set.
=> auth: type the `google` and `facebook` auth config

packages/chaire-lib-backend/src/services/auth/userEmailNotifications.ts
Update the message to make it clear that we send both a user and admins messages
=> Update log message when sending account creation email

packages/transition-frontend/src/components/forms/line/__tests__/TransitLineButton.test.tsx, packages/transition-frontend/src/components/forms/line/__tests__/__snapshots__/TransitLineButton.test.tsx.snap, packages/transition-frontend/src/components/forms/service/TransitServiceButton.tsx, packages/transition-frontend/src/components/forms/service/TransitServiceEdit.tsx, packages/transition-frontend/src/components/forms/service/TransitServiceLineItem.tsx, packages/transition-frontend/src/components/forms/service/TransitServiceLinesDetail.tsx
Enhance Service View with Line Display and Filtering
Part of [#1010](https://github.com/chairemobilite/transition/issues/1010)
• Added logic to display service lines in both the main Service View and the Edit Panel View
• Implemented filtering to show only relevant lines based on the selected service
• Added TransitServiceLinesDetails to manage line filtering per service
• Updated TransitServiceButton and TransitServiceEdit to integrate the new component
• Hid unnecessary line information to streamline the UI
• Renamed elements to align with French naming conventions
Added tests (TransitLineButton.test.ts) to ensure correct behavior after modifying display options
=> Enhance Service View with Line Display and Filtering

packages/chaire-lib-common/src/services/routing/OSRMRoutingService.ts, packages/chaire-lib-common/src/services/routing/RoutingResultUtils.ts, packages/chaire-lib-common/src/services/routing/RoutingService.ts, packages/chaire-lib-common/src/services/routing/__tests__/OSRMRoutingService.test.ts, packages/transition-backend/src/services/transitRouting/TrRoutingBatch.ts
fixes #1263 
This greatly reduces the size of the json object response in the batch results:
For example, a result (with error in the transit results) had an original size of 48 241 bytes and finished with 1 111 bytes. With actual transit routing results (~8km walking distance), it's ~7K bytes. Note that this is the size of the json string of the result and does not reflect how it is saved in the database.  These numbers are not directly transferrable to database size of this data, but it gives an idea.
=> batch route: return only known fields and do not save geometries if not requested

.dockerignore, Dockerfile, README.md, docker-dev/docker-compose.override.yml, docker-dev/entrypoint-dev.sh, docs/devWithDocker.md
New docker development environment for quick code updates.
>Note: Debugging with breakpoints has not been tested yet
Created a new `docker-dev/` folder with its own `Dockerfile` and `docker-compose.yml`
* The new `Dockerfile` is optimized to rebuild the image faster in case of a code change 
* Moved `COPY . /app` to the last possible moment. This way, the docker image doesn't need to be rebuilt entirely for every file change. Some directories did still need to be copied earlier though.
* Moved `yarn compile` right before 1. . This also keeps from rebuilding almost the entire stack when editing code.
* Changed the `CMD` that starts the app. It now executes the file `entrypoint-dev.sh` (see below)
* `docker-dev/docker-compose.yml` has new bind-mounts to map volumes from the source code of …
=> Add a Docker environment for development (#45)

.github/workflows/build-docker-image.yml
We don't want it to run on people's forks
=> Restrict the build docker workflow to run only on the official repo

packages/chaire-lib-common/src/utils/LodashExtensions.ts, packages/chaire-lib-common/src/utils/__tests__/LodashExtensions.test.ts
We trim() string to ensure that whitespaces are considered blank
Added unittest to match those cases
Closes: #1281
=> isBlank: Consider whitespaces as blank

packages/transition-backend/src/services/transitRouting/TrRoutingBatch.ts
When running batch routing, we have a log which show the rate of calculation since the beginning of the run. Since the rate can be non constant, we want to see what is the current rate.
We calculate the rate between 2 log entries, by saving what were the values when we previously displayed the log.
New log:
calc/sec: 2.23 (current: 2.23)
calc/sec: 3.14 (current: 4.91)
calc/sec: 3.35 (current: 3.8)
Closes: #1262
=> Add current calculation rate to log message

packages/transition-common/src/services/path/PathGeographyUtils.ts, packages/transition-common/src/services/path/__tests__/PathGeographyUtils.test.ts
fixes #1291
If any of the terminal node has a manual type (like with the temporary click on the map), it may be in a zone where there is no network, so we'll use the manual routing service to route this path.
=> path: use manual routing for direct path when terminals are manual

examples/config.js, packages/chaire-lib-backend/src/config/server.config.ts, packages/chaire-lib-common/src/config/__tests__/Preferences.test.ts, packages/chaire-lib-common/src/config/defaultPreferences.config.ts, packages/chaire-lib-common/src/config/shared/project.config.ts, packages/transition-common/src/config/__tests__/project.config.test.ts, packages/transition-common/src/config/project.config.ts, packages/transition-frontend/src/components/dashboard/TransitionMenuBar.tsx, packages/transition-frontend/src/components/forms/preferences/sections/PreferencesSectionGeneral.tsx, packages/transition-frontend/webpack.config.js
fixes #1286
Add a `sections` configuration option in the config of chaire-lib, to be used by applications like Transition or Octavi that use the dashboard functionality of chaire-lib.
Add a `project.config` file in transition-common with the transition section default configuration.
Update the `webpack.config.js` file to make sure the default section config is imported before reading the config file. That is the only change required to account for the new section config option.
Update usages in the frontend to get the enabled sections from the config instead of preferences.
** Breaking change **
Section configurations on the config file's `defaultPreferences` section is now deprecated. They will still work for a while, but they need to be updated.
Configuration files can overwrite section …
=> config: get the section configuration out of preferences

yarn.lock
Delete all the `@babel/*` data from `yarn.lock` and run `yarn` again to get the latest versions. This should fix a few dependabot issues.
=> dep: Update `@babel/*` packages

docker-dev/docker-compose.override.yml, docs/devWithDocker.md
1. The documentation mentions `docker-dev-transition-www-1` as the container name, even though when you follow the instructions, the created container is called `transition-transition-www-1`. The name has been corrected accordingly.
2. When trying to setup the dev environment following the documentation, the command  `docker compose ... up --build` would fail because it would try to pull the app's image. Now the docker compose override file changes the build context and uses the root Dockerfile to build the image.
=> Docker dev environment : 2 small fixes related to the instructions in the documentation

packages/chaire-lib-frontend/src/components/forms/auth/passwordless/PwdLessLoginForm.tsx
fix: #725 
Close https://github.com/chairemobilite/transition/pull/726 when this is merged. It's a duplicate of an old PR.
Fix bug with passwordless login form when pressing 'enter' or 'space'.
Remove onKeyUp on the button because the default button already handles that. On the email input, put onKeyUp with handleKeyUp.
So now, the user can press 'enter' or 'space' directly from the email input and go to the survey directly. Remove e.witch that is deprecated. The new method is e.key.
=> Fix bug with passwordless login form when pressing 'enter' or 'space'.

packages/chaire-lib-frontend/src/components/forms/auth/localLogin/LoginForm.tsx, packages/chaire-lib-frontend/src/components/forms/auth/localLogin/RegisterForm.tsx, packages/chaire-lib-frontend/src/components/forms/auth/passwordless/PwdLessLoginForm.tsx, packages/chaire-lib-frontend/src/components/pages/__tests__/__snapshots__/LoginPage.test.tsx.snap
fix: #1142 
Fix double submit when 'Enter' press inside the form.
We remove onKeyUp inside a form element because this could send the form twice when clicking 'enter' with the submit button focus. 
We move onKeyUp on the last input of the form so the user can submit the form when pressing 'enter' from there. 
We did this correction for LoginForm, RegisterForm, and PwdLessLoginForm. 
There were the same errors for all of them.
Update the packages/chaire-lib-frontend/src/components/pages/__tests__/__snapshots__/LoginPage.test.tsx.snap snapshot with buttons with type 'submit'
=> Fix double submit when 'Enter' press inside the form.

packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/guidance.lua, packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/walking.lua
OSRM Profile: Define side_road_multiplier for walking.lua
There was one way that define a side_road as "yes" that was processed by the walking
profile. Since we use the way_handlers:penalties, we need to define the
value side_road_multiplier, other it will propagate as nil
The offending way was https://www.openstreetmap.org/way/1204310256
Also sync guidance from upstream
=> Fix lua profile

.github/workflows/transition.yml
The latest version of the toolchain does not work with some of the old dependencies that we have in json2capnp. Until we fix/change json2capnp, let's pin the test to the last working of the rust toolchain
=> Pin version of rust toolchain to use for json2capnp test

.github/workflows/transition.yml, Dockerfile, packages/chaire-lib-backend/src/utils/processManagers/ProcessManager.ts, packages/chaire-lib-backend/src/utils/processManagers/TrRoutingProcessManager.ts, packages/chaire-lib-backend/src/utils/processManagers/__tests__/ProcessManager.test.ts, packages/chaire-lib-backend/src/utils/processManagers/__tests__/TrRoutingProcessManager.test.ts
With trRouting now supporting memcached for caching access/egress nodes calculation, we can benefit with some speed up in batch calculation. This is true when a batch calculation have many points that are repeated (either origin or destination). So not every calculation will benefits from this.
This change add the start of a memcached server before starting trRouting for the batch mode. Also add the parameters to the trRouting call to use this memcached.
In this tests with many repeat location, we can see a significant speed improvement: Before:
transition-www-1  | 2025-04-02T14:26:27.409246640Z calc/sec: 3.57 (current: 3.57) transition-www-1  | 2025-04-02T14:26:34.361172558Z calc/sec: 6.24 (current: 16.25) transition-www-1  | 2025-04-02T14:26:42.618879721Z calc/sec: 8.53 (current: 17.67) …
=> Enable use of memcached for trRouting when doing batch calculation

packages/chaire-lib-backend/src/utils/processManagers/TrRoutingProcessManager.ts, packages/chaire-lib-backend/src/utils/processManagers/__tests__/TrRoutingProcessManager.test.ts
The memcached support have changed the start of trRouting to be in a Shell. it could not connect to memcached in a docker container without it. Alas, this make it impossible to kill trRouting to be stop/restart with the current method.
Let's move back to useShell=false. This will have trRouting fail to connect to memcached, but that's ok. It still work, but warn about the failed memcached connection.
=> Disable useShell for starting trRouting

packages/transition-frontend/src/components/forms/line/__tests__/__snapshots__/TransitLineButton.test.tsx.snap, packages/transition-frontend/src/components/parts/Button.tsx, packages/transition-frontend/src/components/parts/__tests__/__snapshots__/Button.test.tsx.snap
The class of the image was _icon instead of _icon-alone like its neighboring images, which caused it to shrink when the name took too much space. Changing the class fixes the problem.
Fix: #1307
=> Fix the duplicate icon getting smaller when a name is too long.

packages/chaire-lib-backend/src/config/auth/__tests__/passwordless.config.test.ts, packages/chaire-lib-backend/src/config/auth/passwordless.config.ts, packages/chaire-lib-backend/src/services/auth/__tests__/userEmailNotifications.test.ts, packages/chaire-lib-backend/src/services/auth/userEmailNotifications.ts
Since this attribute is only used to display an error message that is prone to misinterpretation when the email is null or undefined, we have removed it. The email attribute's type was changed to just be string as a result, and the type verification has been moved to a new function that is called before sendEmail(). Fix: #836
=> Remove the id attribute of userEmailData

packages/chaire-lib-backend/package.json, packages/chaire-lib-backend/src/services/auth/userPermissions.ts, packages/chaire-lib-common/package.json, packages/chaire-lib-frontend/package.json, packages/chaire-lib-frontend/src/services/auth/authorization.ts, yarn.lock
fixes #1097
The `Ability` type is deprecated and is simply replaced with the `MongoAbility` interface and the `createMongoAbility` factory function instead of a constructor.
=> dep: Update @casl/ability from 5.4.4 to 6.7.3

packages/transition-frontend/src/components/dashboard/TransitionDashboard.tsx, packages/transition-frontend/src/components/forms/preferences/sections/PreferencesSectionGeneral.tsx
fixes #1362
Add a `noBlank` prop to the `infoPanelPosition` preferences selection. Also, the value will be shown as left only if the value of the preference is `left`, otherwise, the right will be shown.
In the `TransitionDashboard` component, since we have only 2 possible positions, left or right, we put the panel on the left if and only if the value of the preference is left. Otherwise, we put it on the right. No instead of checking equality with `right`, we check inequality with `left`. That can be revisited when we support more placement options.
=> preferences: Make sure `infoPanelPosition` cannot be blank

packages/chaire-lib-frontend/package.json, packages/chaire-lib-frontend/src/components/pageParts/Header.tsx, packages/chaire-lib-frontend/src/config/i18n.config.ts, yarn.lock
fixes #1129
The package is 5 years old and not necessary in Transition
=> dep: Remove dependency to `moment-business-days`

yarn.lock
The `socket.io-parser@*' dependency is not used, it is only required because of the types packages that depend on it. So we use the same version as the one we actually use, to remove a security alert on the 4.2.1 version.
=> dep: Update dependency to `socket.io-parser`

yarn.lock
=> dep: bump version of `debug` from 3.2.6 to 3.2.7

packages/chaire-lib-backend/src/models/db/__tests__/dataSources.db.test.ts, packages/chaire-lib-backend/src/models/db/__tests__/preferences.db.test.ts, packages/chaire-lib-backend/src/models/db/__tests__/tokens.db.test.ts, packages/chaire-lib-backend/src/models/db/__tests__/users.db.test.ts, packages/chaire-lib-backend/src/models/db/__tests__/zones.db.test.ts, packages/transition-backend/src/models/db/__tests__/TransitPath.db.test.ts, packages/transition-backend/src/models/db/__tests__/TransitSchedule.db.test.ts, packages/transition-backend/src/models/db/__tests__/batchRouteResults.db.test.ts, packages/transition-backend/src/models/db/__tests__/jobs.db.test.ts, packages/transition-backend/src/models/db/__tests__/odPairs.db.test.ts, packages/transition-backend/src/models/db/__tests__/places.db.test.ts, packages/transition-backend/src/models/db/__tests__/simulationRuns.db.test.ts, packages/transition-backend/src/models/db/__tests__/simulations.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitAgencies.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitLines.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitNodeTransferable.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitNodes.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitScenarios.db.test.ts, packages/transition-backend/src/models/db/__tests__/transitServices.db.test.ts
By adding `await knex.destroy()` in the `afterAll` block of each database tests, we make sure that the connection is properly destroyed, synchronously, and the tests can exit without open handles.
Some tests already called the `destroy` db query from some tables, but this function was effectively destroying the connection multiple times (as all queries share the same connection) and it was not done synchronously as no callback was passed to the function, so the test was still finishing with open handles.
=> tests: destroy connection after db tests

packages/chaire-lib-backend/src/api/__tests__/uploads.socketRoutes.test.ts, packages/chaire-lib-backend/src/api/uploads.socketRoutes.ts
fixes #1375
The `socket.io-file` package used to create the directory where to upload the file if it did not exist. When this package was replaced by our own code, this behavior was not replicated. We now create the directory if it does not exist before saving the file.
=> file upload: create directory before uploading file

packages/chaire-lib-backend/src/services/auth/__tests__/anonymousLoginStrategy.test.ts, packages/chaire-lib-backend/src/services/auth/anonymousLoginStrategy.ts
fixes #1389
When the new user is created with the anonymous login strategy, the `recordLogin` method is called.
=> auth: record login in the anonymous strategy

packages/chaire-lib-backend/src/api/__tests__/auth.routes.test.ts, packages/chaire-lib-backend/src/api/auth.routes.ts
fixes #1392
Setting the routes on a router gives more flexibility to the caller to add middleware and prefix the paths to the auth routes.
The app is a `Router`, but the reverse is not true. So we do not need to change the way those routes are set in the Transition app, as the express application in Transition is quite simple.
=> auth: pass a router to setup auth routes instead of app

packages/chaire-lib-backend/src/api/__tests__/captcha.routes.test.ts, packages/chaire-lib-backend/src/api/captcha.routes.ts, packages/chaire-lib-frontend/src/components/captcha/CapJsCaptcha.tsx
By default, once a cap.js token is validated, it is deleted and cannot be reused by any other query. This is not desirable, for example, in case of login, where legitimate errors can occur and the user may need to re-submit a modified form. He should not have to re-do the captcha every time.
This adds an option to the captcha middleware, a boolean `keepToken` value, which can be set per route, such that a query that should succeed everytime (like help request) can delete the token, while others, like login, can keep the token between queries.
Note that cap.js does a garbage collection of the expired token in any case, this option only applies to the current query.
=> captcha: allow to keep a token after validation

.github/workflows/build-docker-image.yml
This branch can be used to test the declared trip validation functionality.
=> ci: add `validationTrajets` branch to docker builds

packages/transition-backend/src/server.ts, packages/transition-backend/src/socketServerApp.ts, packages/transition-backend/src/tasks/serverWorkerPool.ts
The routing and workerpool had not link to the socket.io setup, so we move them into the server.ts file.
Created a new function setupRouting that deal with OSRM, cache creation and trRouting. Reworked the await so that we can start OSRM and recreate the cache in parallel for a small startup speed up.
Moved the code that was in server.ts into a setupAll() function, so that we can use await there. We call the setupRouting and await at the end, before enqueuing the batch job. That way, we can start the webapp and socket.io before the routing is fully setup. Since we wait after the routing await to enqueue the batch job, this will not create a issue and solve #898
=> Move the non-socket.io setup bits directly into server.ts

packages/chaire-lib-frontend/package.json
This puts the icons in a directory that is expected to be public and distributed along with the `chaire-lib-frontend` package. It ignores the `sources` directories.
webpack can then copy those files in the `dist` directory to publish them
=> icons: copy the icon files in the `lib` directory

locales/en/transit.json, locales/fr/transit.json, packages/chaire-lib-frontend/src/components/pageParts/FormErrors.tsx, packages/transition-frontend/src/components/forms/schedules/TransitScheduleBatchList.tsx
fixes #1401
The algorithm for batch edit does not yet support lines with only one
path, so those lines are not displayed in the list. This caused
questioning for the users who were looking for those lines. The warning
explains why some lines may not be there.
=> schedules: warn for batch edit not displaying one path lines
