Dockerfile

Updating to debian stable instead of oldstable

Update dockerfile to build with bullseye instead of buster

---

.gitignore
packages/chaire-lib-backend/package.json
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/access.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/destination.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/guidance.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/maxspeed.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/measure.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/pprint.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/profile_debugger.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/relations.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/sequence.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/set.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/tags.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/utils.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/way_handlers.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/lib/way_handlers_way_data_as_name.lua
yarn.lock

They were not noticed as their path is in the .gitignore

Add lib/*.lua files for the osrmProfiles

---

CONTRIBUTING.md
README.md
examples/README.md

* Add a CONTRIBUTING.md file with instructions to contribute to the community, code, test and debug the application
* Update the main README to contain all the documentation required to run a new instance of Transition.

doc: Improve starting documentation

---

packages/transition-frontend/webpack.config.js

Fixes #427
Move to the top of the files the variables that are hard-coded and whose name we could want to change eventually.
Remove unused environment variables from the configuration on the client.

Clean up webpack.config file

---

.github/workflows/transition.yml
README.md
packages/chaire-lib-backend/package.json
packages/chaire-lib-common/package.json
packages/chaire-lib-frontend/package.json
packages/transition-backend/package.json
packages/transition-common/package.json
packages/transition-frontend/package.json

Fixes #480
And make our workflow run on both 16.x and 18.x

Upgrade node minimal version to 16.0

---

packages/chaire-lib-common/src/tasks/dataImport/downloadOsmData.ts
packages/chaire-lib-common/src/tasks/osrm/downloadOsmNetworkData.ts
packages/chaire-lib-common/src/utils/osm/OsmOverpassDownloader.ts

This clarify the functions role, where they to the download themselves and write the data to disk. (And not write data passed to them)

Rename OsmOverpassDownloader write functions to fetchAndWrite

---

packages/chaire-lib-frontend/src/components/input/FileUploaderHOC.tsx

Add an uploadStatus props, which passes the state of the FileUploaderHOC with the status of the file upload: notUploaded, uploading (with a progress), error, completed or aborted.
This prop can be used by consumer to track the upload status and know when the upload is completed.

fileUploaderHOC: Add a prop to track status of upload

---

packages/chaire-lib-common/src/config/osm/overpassQueries/networksPolyForOsrm.ts

Forgot that one in the previous PR

Double timeout for overpass query

---

packages/transition-backend/src/socketServerApp.ts

Fixes #597
Batch calculations require the cache to exist. If we run the cache creation asynchronously, tasks may be restarted/enqueued before it is completed and the results will be wrong at best and potentially invalid if the trRouting server starts with incomplete data. We should wait for the cache to be completely saved before allowing client connections.

Wait for cache creation before the socket server starts

---

package.json

This PR adds a fix for the setup of the test DB that was already implemented for the migration.
To test : Sequential tests pass and fail randomly on my end, but seem to always pass on other computers.

Fix migrate-test script missing config parameter

---

packages/transition-backend/src/services/transitRouting/TrRoutingBatch.ts

Fixes #628
If a batch route operation is resumed after server start, the completed trips count is initialized at the current checkpoint instead of 0.

batchRoute: Start the progress at current step when resuming

---

packages/chaire-lib-backend/src/api/__tests__/preferences.socketRoutes.test.ts
packages/chaire-lib-backend/src/api/auth.routes.ts
packages/chaire-lib-backend/src/api/preferences.socketRoutes.ts
packages/chaire-lib-common/src/config/Preferences.ts
packages/chaire-lib-common/src/config/__tests__/Preferences.test.ts
packages/chaire-lib-frontend/src/services/map/events/GlobalMapEvents.ts
packages/transition-common/src/services/accessibilityMap/TransitAccessibilityMapRouting.ts
packages/transition-common/src/services/transitDemand/TransitDemandFromCsv.ts
packages/transition-common/src/services/transitRouting/TransitRouting.ts
packages/transition-frontend/src/services/map/PathMapLayerManager.ts

preferences: Support socket or fetch routes to load/save

---

packages/chaire-lib-backend/src/api/auth.routes.ts

It's the type that is expected from the preferences fetch, similar to the preferences load route.

auth routes: Return a Status for update/reset preferences

---

packages/chaire-lib-backend/src/models/db/__tests__/zones.db.test.ts
packages/chaire-lib-backend/src/models/db/zones.db.queries.ts

This adds a db query receiving a feature in parameter, as well as an optional data source id and retrieves the zones intersecting this geometry. The data source shortname and name are retrieved in addition to the complete zone data.

zones: Add a db query to get zones intersecting geometry

---

locales/en/auth.json
locales/fr/auth.json
packages/chaire-lib-frontend/src/components/forms/auth/passwordless/PwdLessLoginForm.tsx

+ add placeholder for email in pwdless login form

remove autofocus on email for mulitple login choices

---

packages/transition-frontend/src/components/map/TransitionMainMap.tsx

When working offline, without internet access, the mapbox style cannot be fetched from mapbox and the main map will be in error. The 'load' event won't be called and the 'map.loaded' event, which triggers the data fetch is never called, either, causing the application to be empty, but the user is still able to go to the various menus.
We add a listener on the 'error' event of the map and if the map is not loaded already call the 'map.loaded' event. Even if the map data cannot be displayed, the data can still be navigated in the application. It should not display an empty application.

mainMap: Emit 'map.loaded' event on map error

---

packages/chaire-lib-backend/src/config/auth/index.ts

auth: sanitize user for subsequent external logins

---

packages/chaire-lib-frontend/src/components/pageParts/Header.tsx

So we can control it using CSS
cc @tahini

header: add an id to the username item

---

packages/transition-backend/src/services/gtfsImport/ScheduleImporter.ts
packages/transition-backend/src/services/gtfsImport/__tests__/ScheduleImporter.test.ts

fixes #728
When frequencies are specified for a trip, the specified stop times should be ignored and simply start/end according to frequencies information.

gtfsImport: fix handling of frequencies

---

packages/chaire-lib-backend/src/api/trRouting.routes.ts
packages/chaire-lib-backend/src/utils/trRouting/TrRoutingServiceBackend.ts
packages/chaire-lib-common/src/api/TrRouting/base.ts
packages/chaire-lib-common/src/api/TrRouting/index.ts
packages/chaire-lib-common/src/api/TrRouting/trRoutingApiV2.ts
packages/chaire-lib-common/src/services/trRouting/TrRoutingService.ts
packages/chaire-lib-common/src/services/trRouting/__tests__/TrRoutingService.test.ts
packages/chaire-lib-common/src/test/services/trRouting/TrRoutingServiceMock.ts
packages/transition-backend/src/api/__tests__/services.socketRoutes.test.ts
packages/transition-backend/src/api/services.socketRoutes.ts
packages/transition-backend/src/services/transitRouting/TrAccessibilityMapBatchResult.ts
packages/transition-common/src/services/accessibilityMap/TransitAccessibilityMapCalculator.ts
packages/transition-common/src/services/accessibilityMap/__tests__/TransitAccessibilityMapCalculator.test.ts

See individual commits for details

trRouting: Use v2 api for accessibility map

---

packages/transition-backend/src/server.ts

This allows to catch and log startup errors

Add try/catch around server start

---

locales/en/transit.json
locales/fr/transit.json
packages/transition-frontend/src/components/forms/schedules/TransitScheduleEdit.tsx

Fixes #337
This field is the time from which there are no more departure for the period.

schedules: Add a custom end time field to the edit form

---

.vscode/settings.json
packages/chaire-lib-backend/src/services/auth/userEmailNotifications.ts

Add send welcome email
I'm going to use this, to send welcome Email for survey that have this config.
I'm going to put this sendWelcomeEmail function inside Evolution: evolution\packages\evolution-backend\src\services\auth\participantAuthModel.ts createAndSave().

Add send welcome email

---

packages/chaire-lib-backend/src/utils/processManagers/TrRoutingProcessManager.ts
packages/chaire-lib-backend/src/utils/processManagers/__tests__/TrRoutingProcessManager.test.ts
packages/chaire-lib-backend/src/utils/trRouting/TrRoutingServiceBackend.ts
packages/transition-backend/src/services/simulation/SimulationRun.ts
packages/transition-backend/src/services/transitRouting/TrAccessibilityMapBatch.ts
packages/transition-backend/src/services/transitRouting/TrRoutingBatch.ts
packages/transition-backend/src/services/transitRouting/__tests__/TrAccessibilityMapBatch.test.ts
packages/transition-backend/src/services/transitRouting/__tests__/TrRoutingBatch.test.ts
packages/transition-common/src/services/accessibilityMap/TransitAccessibilityMapCalculator.ts

Splitted into 3 commits: 
* Use threaded TrRouting for the normal case
* Adapt batch routing and batch accessibility map
* Fix port configuration for batch accessibility

Use threaded TrRouting

---

packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/walking.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/walking_no_penalty.lua
packages/chaire-lib-backend/src/utils/processManagers/osrmProfiles/walking_way_data_as_name.lua

add trunk with greater penalty for walking

update lua profiles for walking to top at 5 km/h

---

locales/en/notifications.json
locales/fr/notifications.json
packages/chaire-lib-common/src/config/osm/overpassQueries/streets.overpassql
packages/chaire-lib-common/src/config/osm/overpassQueries/streets.ts
packages/transition-backend/src/api/__tests__/osm.socketRoutes.test.ts
packages/transition-backend/src/api/all.socketRoutes.ts
packages/transition-backend/src/api/osm.socketRoutes.ts
packages/transition-backend/src/api/transit.socketRoutes.ts
packages/transition-backend/src/services/nodes/NodeCollectionUtils.ts
packages/transition-backend/src/services/nodes/__tests__/NodeCollectionUtils.test.ts
packages/transition-backend/src/services/osm/OsmGetStreetsAroundPoint.ts
packages/transition-backend/src/services/osm/__tests__/OsmGetStreetsAroundPoint.test.ts
packages/transition-backend/src/services/path/__tests__/PathGtfsGeographyGenerator.test.ts
packages/transition-common/src/services/nodes/NodeGeographyUtils.ts
packages/transition-common/src/services/nodes/__tests__/NodeGeographyUtils.test.ts
packages/transition-frontend/src/components/forms/node/TransitNodeEdit.tsx
packages/transition-frontend/src/services/map/events/NodeSectionMapEvents.ts

get street names from osm around node

---

packages/chaire-lib-common/src/config/lineModesDefaultValues.ts

alow higher running speeds for transferable mode

---

pyTransition/.gitignore
pyTransition/CONTRIBUTING.md
pyTransition/LICENSE
pyTransition/README.md
pyTransition/pyTransition/__init__.py
pyTransition/pyTransition/transition.py
pyTransition/setup.py
pyTransition/tests/test_transition.py

pyTransition is a Python package designed to interact with the public API of the transit planning application Transition. It allows users to retrieve and request geographic and routing data from the app.

pyTransition: Added pyTransition source code

---

pyTransition/pyTransition/transition.py
pyTransition/setup.py
pyTransition/tests/test_transition.py

This allow to test if our Transition object can establish a connection to the server

pyTransition: add an is_token_valid function

---

packages/chaire-lib-backend/src/config/knexfile.ts

db: Log database and schema used when starting the server

---

docs/APIv1/API.yml
docs/APIv1/summary.yml
packages/chaire-lib-common/src/services/routing/SummaryAttributes.ts
packages/chaire-lib-common/src/services/routing/__tests__/SummaryAttributes.test.ts
packages/transition-backend/src/api/__tests__/public.routes.test.ts
packages/transition-backend/src/api/public.routes.ts

La requete API "summary" de trRouting a ajoutee a l'API de transition. Fix: #1031

Ajoute de summary a API transition

---

packages/transition-frontend/src/components/forms/node/TransitNodePanel.tsx

Add a title and icon to the Stop Nodes submenu in the right panel.

---

.github/workflows/transition.yml
Dockerfile

Only test and build on Node 22. Also switch Docker build

Switch to node 22

---

packages/chaire-lib-frontend/src/components/forms/auth/localLogin/LoginForm.tsx
packages/chaire-lib-frontend/src/components/pages/__tests__/__snapshots__/LoginPage.test.tsx.snap

Login page autofocuses on username instead of password

---

examples/config.js
packages/chaire-lib-common/src/config/shared/project.config.ts

And document all those possible options in the example config.js file

config: Add doc and options on auth config parameters

---

packages/transition-backend/file/definitions/definitions-en.tex
packages/transition-backend/file/definitions/definitions-fr.tex

translate definition file in english

---

packages/chaire-lib-frontend/src/styles/_dashboard.scss
packages/chaire-lib-frontend/src/styles/_leftMenu.scss

fix left menu titles not appearing when hovering

---

docs/APIv1/API.yml
docs/APIv1/agencies.yml
docs/APIv1/lines.yml
docs/APIv1/services.yml
docs/index.html
packages/transition-backend/src/api/__tests__/public.routes.test.ts
packages/transition-backend/src/api/public.routes.ts
packages/transition-backend/src/api/public/AgenciesAPIResponse.ts
packages/transition-backend/src/api/public/LinesAPIResponse.ts
packages/transition-backend/src/api/public/ServicesAPIResponse.ts

Add endpoints to get the agencies, services and lines
Add an endpoint to get the supported versions
Add the x-added-in-version extension to the yaml documentation

public API: Add new endpoints

---

packages/chaire-lib-common/src/utils/osm/OsmOverpassDownloader.ts
packages/chaire-lib-common/src/utils/osm/__tests__/OsmOverpassDownloader.test.ts

The download Osm data task worked incorrectly in the step where the geojson is written to a file, resulting in an incorrectly formatted geojson. This commit changes it so the geojson is formatted correctly, and adds a test to verify it.

Fix 1_downloadOsmDataToFiles task.

---

packages/transition-frontend/src/components/forms/scenario/TransitScenarioPanel.tsx

fixes #1208
The agencies, lines and services collections need to be loaded to create a new scenario. So the scenario panel shows a loading state until all those collections, as well as the scenarios collection are loaded.

scenarios: show panel as loading if data not ready

---

packages/chaire-lib-frontend/src/components/routers/PrivateRoute.tsx
packages/chaire-lib-frontend/src/components/routers/PublicRoute.tsx
packages/transition-frontend/src/app-transition.tsx
packages/transition-frontend/src/components/routers/TransitionRouter.tsx

The routes are now components that wrap a route to make sure required permissions are granted. These components can use the auth state directly to know if the person is authenticated or get the current user. This avoids having to pass them as props and simplifies the components.

routes: refactor private and public route elements

---

.github/workflows/build-docker-image.yml
.github/workflows/test-docker-build.yml

First workflow will test docker build on each PR
Second will build the docker image and push to both docker hub and github package repo

Add github workflow to build docker images

---

.github/config-for-github-ui-tests.js
.github/workflows/transition.yml
.github/workflows/ui-tests.yml
.gitignore
CONTRIBUTING.md
configs/base.eslintrc.json
examples/README.md
packages/transition-frontend/.eslintignore
packages/transition-frontend/jest.config.js
packages/transition-frontend/package.json
packages/transition-frontend/playwright-example.config.ts
packages/transition-frontend/ui-tests/languageTestHelpers.ts
packages/transition-frontend/ui-tests/login-tests.spec.ts
packages/transition-frontend/ui-tests/loginTestHelpers.ts
packages/transition-frontend/ui-tests/test-left-menu.spec.ts
packages/transition-frontend/ui-tests/testHelpers.ts
yarn.lock

Add Playwright to Transition so that we can run UI tests, and add tests to log in and navigate through all the tabs.
Fix: #1065

Add Playwright

---

packages/chaire-lib-frontend/src/components/routers/PrivateRoute.tsx
packages/transition-frontend/src/components/dashboard/TransitionToolbar.tsx

* A missing `key` in MenuItem in the toolbar
* A selector returning a different value with the same parameters

Remove 2 warnings and errors from the console

---

packages/chaire-lib-backend/src/services/files/__tests__/CsvFile.test.ts
packages/chaire-lib-backend/src/services/files/__tests__/testFiles/test.csv
packages/chaire-lib-common/src/utils/files/CsvFile.ts
packages/chaire-lib-common/src/utils/files/__tests__/CsvFile.test.ts
packages/chaire-lib-common/src/utils/files/__tests__/test.csv
packages/chaire-lib-common/src/utils/files/__tests__/test_spaces_in_header.csv

trim spaces at the beginning and at the end of each header column, closes #1271

accept spaces in csv header between columns

---

packages/chaire-lib-backend/src/config/i18next.ts
packages/chaire-lib-backend/src/services/auth/userEmailNotifications.ts

And allow user email notification to be overwritten with `customServer` namespace

Read `yaml` files on the server for translations

---

packages/transition-backend/src/services/evolutionaryAlgorithm/candidate/LineAndNumberOfVehiclesNetworkCandidate.ts
packages/transition-backend/src/services/simulation/SimulationRun.ts

Add a TODO
And an additional field in a console log

simulation: Update comment and TODO
